### ISSUE TITLE
v1.0.0-beta Errors

### ISSUE THREAD

**Issue by skynet** [rollbar/rollbar-php#100]
If using the dev version dashboard is flooded with Rollbar's own errors:

`API error: Invalid format. data.body.trace.exception.class is missing and it is required.`

**Comment by dlsteuer** [comment]
@skynet can you send me a link to your account at support@rollbar.com so I can investigate the invalid payload?

**Comment by sluchznak** [comment]
@skynet you using docker alpine image? Your version rollbar is lower then 1.0.0-beta? Probably your problem in iconv extension.

**Comment by MichaelMackus** [comment]
:+1: 

I'm on git SHA a71c590123a0b7b2272881a340813336faf35f3a and I'm getting these errors on PHP v7.0 whenever there's a PHP syntax error. Perhaps something to do with the new `\Throwable` interface in PHP 7?
