### ISSUE TITLE
Support the Forwarded (RFC 7239) header

### ISSUE THREAD

**Issue by jasny** [rollbar/rollbar-php#102]
The `Forwarded` header is the new standard ([RFC 7239](https://tools.ietf.org/html/rfc7239#section-5.4)) als alternative for the common (but non-standard) `X-Forwarded-*` headers.

>   This document defines an HTTP extension header field that allows
>    proxy components to disclose information lost in the proxying
>    process, for example, the originating IP address of a request or IP
>    address of the proxy on the user-agent-facing interface.  In a path
>    of proxying components, this makes it possible to arrange it so that
>    each subsequent component will have access to, for example, all IP
>    addresses used in the chain of proxied HTTP requests.

It is passed to PHP as `$_SERVER['HTTP_FORWARDED']`. It needs to be parsed to extract the different parts.

> ```
>   X-Forwarded-For: 192.0.2.43, 2001:db8:cafe::17
> ```
> 
>   becomes:
> 
> ```
>   Forwarded: for=192.0.2.43, for="[2001:db8:cafe::17]"
> ```

**Comment by ArturMoczulski** [comment]
This is implemented in PR #155
