### ISSUE TITLE
using the Level class first causes a Fatal error

### ISSUE THREAD

**Issue by downsider** [rollbar/rollbar-php#103]
Ran into a bug where I used one of the `Level` constants before accessing the rollbar class. I'm using an autoloader, so the files are only loaded when required.

As the first line in `rollbar.php` is to include `Level.php`, which had already been loaded by that point, it tried to redeclare the class, causing a Fatal error

**Comment by downsider** [comment]
I was using version 0.18.2
I've made a fix for this, but which branch should I PR it into?

**Comment by dlsteuer** [comment]
Hey thanks for that, good call. I've just created a new branch in the repo called release-maintenance, can you do the pull request against that branch, and then I can draft a new 0.18.3 release

**Comment by andywaite** [comment]
Also experiencing this problem. What's the status on this?

**Comment by andywaite** [comment]
Wouldn't the easiest thing to be to swap the include to a require_once?

**Comment by ArturMoczulski** [comment]
This is solved and not relevant anymore in latest master. The library has been completely restructured and currently loading is managed by composer and autoloading.
