### ISSUE TITLE
API error: Invalid format 

### ISSUE THREAD

**Issue by sluchznak** [rollbar/rollbar-php#104]
API error: Invalid format. data.body must not be undefined. Instead, it should be an object with a 'message', 'trace', 'trace_chain', or 'crash_report' key.

tried different versions:
baibaratsky/yii2-rollbar:1.4.* (rollbar-php:0.18.2)
baibaratsky/yii2-rollbar:1.1.0 (rollbar-php:0.15.0)

**Comment by sluchznak** [comment]
Sorry, my bad. This problem with docker php alpine image and iconv extension

**Comment by andrewmclagan** [comment]
How did you resolve this? very same issue?

**Comment by sluchznak** [comment]
refused from docker alpine image

**Comment by andrewmclagan** [comment]
Refused?

**Comment by sluchznak** [comment]
we replaced docker php alpine image with full docker php image

**Comment by sluchznak** [comment]
sorry for my bad english
