### ISSUE TITLE
Handle PHP 7 predefined exceptions

### ISSUE THREAD

**Issue by joshuabaker** [rollbar/rollbar-php#107]
In PHP 7 there are various [predefined/reserved exceptions](http://php.net/manual/en/reserved.exceptions.php), which are not currently handled by the Rollbar package.
- [`Error`](http://php.net/manual/en/class.error.php)
- [`ArithmeticError`](http://php.net/manual/en/class.arithmeticerror.php)
- [`AssertionError`](http://php.net/manual/en/class.assertionerror.php)
- [`DivisionByZeroError`](http://php.net/manual/en/class.divisionbyzeroerror.php)
- [`ParseError`](http://php.net/manual/en/class.parseerror.php)
- [`TypeError`](http://php.net/manual/en/class.typeerror.php)

[`Error`](http://php.net/manual/en/class.error.php) is the base class for all internal PHP errors, so could be caught via instance type checking. Whilst there is no common interface defined, the interfaces do actually match exactly with the standard `Exception` class.

**Comment by jondeandres** [comment]
Hi @joshuabaker, sorry for the delay. Which version of rollbar-php are you using? We released v1.0.0-beta version, https://packagist.org/packages/rollbar/rollbar, which takes care of the php version to decide which base exception class to use.

In case of php >= 7.0 we use `Throwable` as the base class, which is used by `Error` and `Exception`.

**Comment by joshuabaker** [comment]
I believe we’re using the stable release, which explains that. Is the beta safe for production?

**Comment by jondeandres** [comment]
@joshuabaker we didn't have important issues with it in last 6 months so we'll release it this week as 1.0.0. You can wait or upgrade to the beta version. We'll not add more changes between 1.0.0-beta and 1.0.0
