### ISSUE TITLE
iconv with alpine docker image

### ISSUE THREAD

**Issue by andrewmclagan** [rollbar/rollbar-php#108]
The logger throws:

```
 iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed in /var/www/vendor/rollbar/rollbar/src/rollbar.php on line 374
```

When run in an alpine linux docker container. 

The issue can temporarily be circumvented by using the config:

`'enable_utf8_sanitization'  => false,` although this is not desierable

**Comment by nocive** [comment]
Had the same problem with alpine with other libraries relying on iconv. Problem can be easily worked around by using ```transliterator_transliterate``` instead (http://php.net/manual/en/transliterator.transliterate.php)

**Comment by rokob** [comment]
This is no longer a thing right? We are not using iconv anymore anywhere.

**Comment by andrewmclagan** [comment]
Sorry no idea... I would like to know though.

**Comment by rokob** [comment]
I am adding this to the 1.0.0 release to remember to close this once we actually make that release. This was taken care of in the code updates to 1.0

**Comment by rokob** [comment]
Closing this as it is fixed in the newest release.
