### ISSUE TITLE
Difference between $extra_data and $payload_data

### ISSUE THREAD

**Issue by martiros** [rollbar/rollbar-php#115]
What is the difference between `$extra_data` and `$payload_data` arguments in `report_exception` function ?

I noticed in web interface rollbar appending `trace.extra.` for `$extra_data`. Is there any other difference?  
<img width="961" alt="_4_illuminate_validation_validationexception__the_given_data_failed_to_pass_validation__-_latechmeetups_com_-_rollbar" src="https://cloud.githubusercontent.com/assets/5350225/22485608/23f67f08-e7bb-11e6-8919-025ca8478c61.png">

**Comment by stclairdaniel** [comment]
I believe the difference is that $extra_data is for optional custom data, whereas $payload_data should conform to the required data as seen in our API docs [here](https://rollbar.com/docs/api/items_post/#data-format)

**Comment by coryvirok** [comment]
Hi @martiros,

We have refactored the SDK quite a bit since this issue was first filed. Is this question still open?

**Comment by marty-mart** [comment]
Hi @coryvirok,

We haven't been upgraded to new SDK yet. But we figured out the answer to the question. Thanks!

**Comment by martiros** [comment]
Hi @coryvirok,

We haven't been upgraded to new SDK yet. But we figured out the answer to the question. Thanks!
