### ISSUE TITLE
Test scrubbing

### ISSUE THREAD

**Issue by rokob** [rollbar/rollbar-php#122]
As per https://github.com/rollbar/rollbar-php/pull/112 scrubbing does not work correctly. There is one test for scrubbing and it obviously does not cover a reasonable amount of surface area. We need better tests around how things are scrubbed.

**Comment by rokob** [comment]
https://github.com/rollbar/rollbar-php/blob/master/tests/DataBuilderTest.php#L152-L163 is the one place that scrubbing is currently tested.

**Comment by rokob** [comment]
I would check out the comments on https://github.com/rollbar/rollbar-php/pull/112 as to the reasoning for those proposed changes to scrubbing are and what the expected behavior is. In general, if a have a key in scrub_fields, we want to replace the value with `********` but we want to do that within recursive structures as well.

**Comment by ArturMoczulski** [comment]
This is covered by PR https://github.com/rollbar/rollbar-php/pull/126
