### ISSUE TITLE
Research test suite compatibility with more recent version of PHPUnit

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php#125]
PHPUnit 4.8.* which we are currently using is two majors behind the current stable. I'll experiment with newer versions and see how much we can upgrade to still remain compatible with PHP 5.3+.

**Comment by coryvirok** [comment]
Any update on this?

**Comment by ArturMoczulski** [comment]
Left it out for now to keep focus on scrubbing and v1.0.0 . I'll get to this in 1.1. @coryvirok what do you think?

**Comment by coryvirok** [comment]
Works for me

**Comment by rokob** [comment]
I'm going to remove this from the 1.1 release because we are not going to up our minimum version to 5.6 yet, but I will leave it open as something to do in the future.

**Comment by rokob** [comment]
I'm actually going to close this as the issues is not a good place for things that can't be done.
