### ISSUE TITLE
Update \Monolog\Handlers\RollbarHandler to support master

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php#128]
The current version of \Monolog\Handlers\RollbarHandler is not compatible with code in master. It requires an instance of RollbarNotifier to be injected in the constructor. RollbarNotifier class has been replaced with RollbarLogger in rollbar/rollbar-php:master

**Comment by ArturMoczulski** [comment]
After further investigation, I can see that current master can be used with Monolog since our Logger is PSR-3 compliant. We need to update the README.md with new instructions how to use it though:

```
		$log = new \Monolog\Logger('SampleRollbarPHP\Monolog');
		$psrHandler = new \Monolog\Handler\PsrHandler(Rollbar::logger());
		$log->pushHandler($psrHandler);
		$log->error($msg);
```

**Comment by alister** [comment]
Adding instructions for how to use Rollbar-php, via aa PSR-3 wrapper, in the MonologBundle configuration would also help me to upgrade to version 1.*.
