### ISSUE TITLE
Mark \Monolog\Handlers\RollbarHandler as deprecated

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php#130]
The RollbarHandler class currently distributed as part of https://github.com/Seldaek/monolog does not support master. Look at #128 for more details.

**Comment by coryvirok** [comment]
Closing since the linked issue has been closed.

**Comment by ArturMoczulski** [comment]
This still needs addressing but it's not anything to do in our code. This is in regards to this part of Monolog package: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RollbarHandler.php

We need to let them know to mark this as deprecated and update so it works with 1.0.0 for backward compatibility. Or do it ourselves and send them a PR.

Either way, we should probably reopen this issue and get to it in 1.1.0
