### ISSUE TITLE
Add backwards compatibility with 0.18.*

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php#132]
Add ::report_message and ::report_exception to Rollbar class for backwards compatibility with 0.18.*. These should be wrappers around the new ::log solution and marked as deprecated.

**Comment by ArturMoczulski** [comment]
Rollbar::flush() also seems to be deprecated. From what I see the batching functionality is just not there in 1.0.0. anymore. I can think of two approaches to go about this:

1. Leave Rollbar::flush() for backwards compatibility and have it do nothing (so users who have those function calls in their code currently do not start getting fatal errors - missing method).
2. Remove Rollbar::flush() completely which will force fatal errors in our user's code and force them to remove these calls if they have any.

@coryvirok @rokob what do you think?

**Comment by brianr** [comment]
Strong vote for option 1. Upgrading to 1.0 shouldn't break customers' code.

**Comment by rokob** [comment]
Merged
