### ISSUE TITLE
DataBuilder::getUrl() expects HTTP_X_FORWARDED_PROTO breaks with multiple forwarded protocols

### ISSUE THREAD

**Issue by amoskyler** [rollbar/rollbar-php#135]
The following method only expects a single value in `HTTP_X_FORWARDED_PROTO`, which is inconsistent with the handling of the `HTTP_X_FORWARDED_FOR` header, which delimits on ',' and pops the last host.

The following code:
```
        if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO'])) {
            $proto = strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']);
        } elseif (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
            $proto = 'https';
        } else {
            $proto = 'http';
        }
```

Should be modified as follows:
```
$parts = explode(',', $_SERVER['HTTP_X_FORWARDED_PROTO'])
$proto = strtolower($parts[0]);
```

**Comment by rokob** [comment]
HTTP_X_FORWARDED_PROTO really should be single valued, but you are right as it is not actually standardized it can be the same as FOWARDED_FOR

**Comment by ArturMoczulski** [comment]
This is ready in PR https://github.com/rollbar/rollbar-php/pull/179
