### ISSUE TITLE
Rollbar doesn't report errors in CLI mode with STDERR piped to /dev/null

### ISSUE THREAD

**Issue by NinoSkopac** [rollbar/rollbar-php#138]
Hey, I don't even know if this is actually an issue, but nevertheless.

Here's how I run my PHP workers:

`nohup /var/www/more/folders/executable.php >/dev/null 2>&1 &`

Whenever the code is broken inside that worker, I don't get it on Rollbar. I run it like this because I don't have a broker in place, and I don't want to wait for worker to finish.

**Comment by ArturMoczulski** [comment]
@NinoSkopac I just tested this and it seems to be working fine. Can you give me a specific example of what kind of "broken code" inside your workers is not logging? What kind of errors or exceptions?

**Comment by NinoSkopac** [comment]
It's been 2 months man, I have no idea. Also, this was for Rollbar 0.x branch.
