### ISSUE TITLE
Undefined index: 0 on line 785 of DataBuilder.php

### ISSUE THREAD

**Issue by danog** [rollbar/rollbar-php#147]
If you log something while passing a json array composed of only numbers as a POST parameter, for example `[1023, 1924]`, the scrub function at line 785 of DataBuilder.php throws an error (undefined index: 0).
This occurs at revision 815f8533ea306374656216b0996098c6120e2102 of the repo

**Comment by rokob** [comment]
I'm working on writing a test for this to see if I can reproduce this failing case.

**Comment by rokob** [comment]
I created a script that throws an exception and logs to rollbar, I called it via cURL:

 `curl -X POST http://localhost:8080/rollbar.php -H "Content-Type: application/json" -d "[1023,1924]"`

and I do not see any errors being thrown and I see the item logged to rollbar along with request.body set to `[1023,1924]`.

Could you give me some more insight into the request you are making that results in the error you describe?

**Comment by danog** [comment]
In my case, the json array is sent as a parameter, not as a raw json payload:

curl -X POST http://localhost:8080/rollbar.php -H "Content-Type: application/json" -F "param=[1023,1924]"

**Comment by rokob** [comment]
I can kinda reproduce this, at least I can see where in the code it is possible to get an undefined index 0 error. I put up a fix and we should get this out in 1.0.1
