### ISSUE TITLE
Remove session id from posted cookie

### ISSUE THREAD

**Issue by drjayvee** [rollbar/rollbar-php#15]
In 5.x, we extended `RollbarNotifier::build_request_data` to strip the session id from the cookie data. In 6.x, that method and the member `_request_data` have been made `private`, so we cannot touch that. (Which is exactly why I dislike "private by default")

`RollbarNotifier::scrub_fields` only applies to `$_POST` and `$_SESSION`, so that can't be used either.

I would propose that Rollbar strip the sesion id (`$_COOKIE[session_name()]`) to prevent session ids from leaking, which is a security risk (because it enables session hijacking). More generally, if `scrub_fields` _were_ applied to headers, users could filter out whatever they want to.

**Comment by dataground** [comment]
Related to https://github.com/rollbar/rollbar-php/issues/52

**Comment by ArturMoczulski** [comment]
In master we don't include any $_COOKIE information in the payload. This issue is not relevant anymore.
