### ISSUE TITLE
Issues with using a custom API endpoint

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar-php#153]
I ran into a few problems using 1.0.1 with a custom endpoint (i.e. sending data to a sandbox instance of Rollbar instead of production):

- I expected the config variable name to be "endpoint", like it is in most/all other notifiers. It's actually `base_api_url`.
  - _Suggestion: add support for `endpoint`, and deprecate `base_api_url`_
- After switching to `base_api_url`, I expected the URL format to be `https://mydomain.com/api/1/`, just like the documented default (`https://api.rollbar.com/api/1/`). However, this did not work - requests via the CurlSender were 404ing. To fix it, I had to change it to `https://mydomian.com/api/1/item/`.
  -  _Suggestion: `endpoint` should expect a url like `https://mydomain.com/api/1/`, not `https://mydomain.com/api/1/item/`_
  - _Second suggestion: research the behavior of base_api_url in rollbar-php 0.18 and ensure that base_api_url works the same way in 1.0.x_

**Comment by rokob** [comment]
Changing `base_api_url` to `endpoint` is a good idea.

Removing `/item/` from the endpoint is also a good idea.

This is not how it used to work, so this should be fixed quickly for backward compatibility

```php
public $base_api_url = 'https://api.rollbar.com/api/1/'
```

**Comment by ArturMoczulski** [comment]
I will submit a PR for this soon.

**Comment by ArturMoczulski** [comment]
Ready for review in https://github.com/rollbar/rollbar-php/pull/189

**Comment by rokob** [comment]
Merged
