### ISSUE TITLE
the config item use_error_reporting is not used in code

### ISSUE THREAD

**Issue by p4ul** [rollbar/rollbar-php#156]
**use_error_reporting**
Sets whether to respect current `error_reporting()` level or not
Default: false

If you search the code this is no longer used. Not sure if this is deliberate?

**Comment by ArturMoczulski** [comment]
I used the PR from vilius-g https://github.com/rollbar/rollbar-php/pull/159 as base for my PR with added test coverage.

This is ready for review and merging.
