### ISSUE TITLE
Remove hard dependency on packfire/php5.3-compat

### ISSUE THREAD

**Issue by elazar** [rollbar/rollbar-php#162]
At this point, PHP 5.3 accounts for less than 1% of all Composer users ([source](https://seld.be/notes/php-versions-stats-2017-1-edition)). The README for this package notes that Composer is the preferred installation method ([source](https://github.com/rollbar/rollbar-php#using-composer-recommended)).

Given this, I believe it would be reasonable to shift from [requiring](https://github.com/rollbar/rollbar-php/blob/1b48a62b86d9c918dcf62ed2a96ca8d06e8eb279/composer.json#L36) the `packfire/php5.3-compat` package to [suggesting](https://getcomposer.org/doc/04-schema.md#suggest) it for PHP 5.3 users. It would make for one less package that the 99% using PHP 5.4 and above have to download and bundle in our builds to be able to use Rollbar.

I'd be happy to submit a PR for this change if it seems reasonable to the maintainers as well.

**Comment by rokob** [comment]
@ArturMoczulski thoughts on this? Is the 5.3-compat package something we think we need? I think we should drop it and add it as a suggestion especially given composer's support for suggestions.

**Comment by rokob** [comment]
A PR would be welcome.

**Comment by elazar** [comment]
@rokob Submitted #169.

**Comment by ArturMoczulski** [comment]
Yeah, this looks good 👍 Thanks for PR
