### ISSUE TITLE
capture_error_stacktraces is not used

### ISSUE THREAD

**Issue by boboldehampsink** [rollbar/rollbar-php#166]
There's no way to disable the use generation of stacktraces anymore.

**Comment by rokob** [comment]
The option `capture_error_stacktraces` used to exist to turn this off but has gone away as of 1.0, this should be added back.

**Comment by ArturMoczulski** [comment]
@rokob Not sure about this. Just went through the log and I can't see any code related to `capture_error_stacktraces` at all. There was documentation in README.md for it, but no actual code.

Either way, I'm going to implement this for 1.2.0

**Comment by ArturMoczulski** [comment]
This is ready for review in PR https://github.com/rollbar/rollbar-php/pull/192

**Comment by rokob** [comment]
Merged
