### ISSUE TITLE
Clean up code climate issues

### ISSUE THREAD

**Issue by rokob** [rollbar/rollbar-php#174]
Code climate has many warnings about the code, one big one is related to a separate issue about our use of static and level. None of them would I consider to be necessarily high priority bugs, but it would be nice to get rid of them all so that future PRs that are only touching old code don't result in erroneous errors.

**Comment by ArturMoczulski** [comment]
I pull #140 into 1.2.0 to refactor the levels which should resolve a lot of Code Climate issues and we have been looking to get this done for a while.

**Comment by ArturMoczulski** [comment]
**For tracking**
There is currently:
224 Code Climate issues
310 Codacy issues

**Comment by ArturMoczulski** [comment]
This is ready for review in PR https://github.com/rollbar/rollbar-php/pull/205
