### ISSUE TITLE
PHP 5.4 issue with php://input

### ISSUE THREAD

**Issue by p4ul** [rollbar/rollbar-php#177]
This function breaks functionality in our script, as it clears out PUT variable body so nothing is returned when our script tries to subsequently access it.

```
    protected function setRequestBody($config)
    {
        $this->requestBody = $this->tryGet($config, 'requestBody');
        
        if (!$this->requestBody) {
            $this->requestBody = file_get_contents("php://input");
        }
    }
```

As file_get_contents("php://input"); can only be called once in older versions of PHP.

See:
Note: Prior to PHP 5.6, a stream opened with php://input could only be read once; the stream did not support seek operations. However, depending on the SAPI implementation, it may be possible to open another php://input stream and restart reading. This is only possible if the request body data has been saved. Typically, this is the case for POST requests, but not other request methods, such as PUT or PROPFIND

**Comment by ArturMoczulski** [comment]
Let me calrify this. In your script you're also trying to access php://input, but now it's empty since it has been already read by Rollbar SDK. Is that correct?

**Comment by p4ul** [comment]
@ArturMoczulski yes

**Comment by ArturMoczulski** [comment]
Solution for this is waiting to be merged https://github.com/rollbar/rollbar-php/pull/181

It's not perfect, but I don't think we can do anything more for PHP < 5.6. This PR disables reading php://input by default and allows to enable it through `include_raw_request_body` config option. It also saves the content of the stream in `$_SERVER['php://input']` in case you still want to access it.

I hope this solves your problem @p4ul
