### ISSUE TITLE
Remove fluent log output from composer test

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php#188]
When I run `composer test` I get a bunch of output from fluent tests not being able to connect to fluent service. This needs to be cleaned up.

**Comment by olafnorge** [comment]
Hi @ArturMoczulski,

I digged a little bit around and found out that, for some reason, the fluent sender is registered as handler when `Rollbar\ReadmeTest::testQuickStart()` gets executed.

```
#0 /var/www/vendor/fluent/logger/src/FluentLogger.php(346): Fluent\Logger\FluentLogger->connect()
#1 /var/www/vendor/fluent/logger/src/FluentLogger.php(390): Fluent\Logger\FluentLogger->reconnect()
#2 /var/www/vendor/fluent/logger/src/FluentLogger.php(363): Fluent\Logger\FluentLogger->postImpl(Object(Fluent\Logger\Entity))
#3 /var/www/src/Senders/FluentSender.php(69): Fluent\Logger\FluentLogger->post('rollbar', Array)
#4 /var/www/src/Config.php(405): Rollbar\Senders\FluentSender->send(Array, 'ad865e76e7fb496...')
#5 /var/www/src/RollbarLogger.php(50): Rollbar\Config->send(Array, 'ad865e76e7fb496...')
#6 /var/www/src/Rollbar.php(69): Rollbar\RollbarLogger->log(Object(Rollbar\Payload\Level), Object(Exception), Array)
#7 /var/www/tests/ReadmeTest.php(37): Rollbar\Rollbar::log(Object(Rollbar\Payload\Level), Object(Exception))
#8 [internal function]: Rollbar\ReadmeTest->testQuickStart()
#9 /var/www/vendor/phpunit/phpunit/src/Framework/TestCase.php(908): ReflectionMethod->invokeArgs(Object(Rollbar\ReadmeTest), Array)
#10 /var/www/vendor/phpunit/phpunit/src/Framework/TestCase.php(768): PHPUnit_Framework_TestCase->runTest()
#11 /var/www/vendor/phpunit/phpunit/src/Framework/TestResult.php(612): PHPUnit_Framework_TestCase->runBare()
#12 /var/www/vendor/phpunit/phpunit/src/Framework/TestCase.php(724): PHPUnit_Framework_TestResult->run(Object(Rollbar\ReadmeTest))
#13 /var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#14 /var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#15 /var/www/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#16 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(149): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#17 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit_TextUI_Command->run(Array, true)
#18 /var/www/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()
#19 {main}> phpcs --standard=PSR1,PSR2 src tests
```

I might be wrong but I think in `Rollbar\FluentTest` the default error handler needs to be restored, because it is running before the `Rollbar\ReadmeTest::testQuickStart()`. Do we have a function for this?

**Comment by olafnorge** [comment]
I think the issue can be found in line https://github.com/rollbar/rollbar-php/blob/master/src/Rollbar.php#L20 because the `$logger` instance is declared as static class variable. In the scope of all tests PHPUnit will be a single process, that means the `Rollbar` instance never gets destructed and stays as long as all tests have been executed.

**Comment by olafnorge** [comment]
But the solution seems quite simple. If we change https://github.com/rollbar/rollbar-php/blob/master/phpunit.xml#L9 to `true` each test gets executed in its own context.

**Comment by olafnorge** [comment]
I created a [PR](https://github.com/rollbar/rollbar-php/pull/197) to close this issue.

Unfortunately one test is failing. I think this is because of the process isolation. Please take a look and advise me how to fix it.

**Comment by olafnorge** [comment]
Hi @ArturMoczulski, hi @coryvirok,

I created an alternative [PR](https://github.com/rollbar/rollbar-php/pull/198) which has a lot more changes but does not fail with test coverage.

But there is still one test failing and I have no idea why.

```
There was 1 failure:

1) Rollbar\DataBuilderTest::testPersonFuncException
Exception in person_fn was not caught.

/var/www/tests/DataBuilderTest.php:638

FAILURES!
Tests: 353, Assertions: 454, Failures: 1.
```

**Comment by olafnorge** [comment]
It seems the `DataBuilderTest::testPersonFuncException` is dependent on any previous test in this unit. If I run the master branch I don't get this error (commented out `FluentTest` before execution).

From my point of view the `DataBuilderTest` needs some refactoring to follow unit test standards like:

- Make each test orthogonal (i.e., independent) to all the others

**Comment by olafnorge** [comment]
Hi. I just saw the PR got merged. I think this issue could be closed then. Cheers.
