### ISSUE TITLE
Laravel support

### ISSUE THREAD

**Issue by jenssegers** [rollbar/rollbar-php#19]
Hi, I have built a package that integrates rollbar with laravel: https://github.com/jenssegers/Laravel-Rollbar

I did run into some trouble because your classes are not namespaced.

**Comment by ArturMoczulski** [comment]
I suggest we provide this as a separate repo that can be optionally pulled in for Laravel projects. So the composer.json require clause would look like this:

```
"require" : {
    "rollbar/rollbar": "1.0.0",
    "rollbar/rollbar-php-laravel": "*"
}
```

@coryvirok @rokob @brianr

**Comment by ArturMoczulski** [comment]
This is finished. We should add https://github.com/rollbar/rollbar-php-laravel to packagist so installation is smooth.

Until then installing the package via composer requires adding the following repository entry to composer.json for Laravel projects:
```json
    "repositories": [
        {
            "type": "vcs",
            "url" : "https://github.com/rollbar/rollbar-php-laravel.git"
        }
    ],
```

**Comment by brianr** [comment]
Related discussion: https://github.com/jenssegers/laravel-rollbar/pull/85

**Comment by rokob** [comment]
rollbar/rollbar-php-laravel needs to get up on packagist but otherwise this is done so closing

**Comment by brianr** [comment]
https://packagist.org/packages/rollbar/rollbar-laravel
