### ISSUE TITLE
Rollbar::log() responds with status 0

### ISSUE THREAD

**Issue by jeliasson** [rollbar/rollbar-php#191]
Dear all,

We're in the process of upgrading Rollbar from version ```0.18.2``` to ```1.0.1```. However, when running ```
Rollbar::log()``` it's not being reported.

```php
Rollbar::init($rollbarInit);
$response = Rollbar::log(Level::error(), $exception);
var_dump($response);
```

**Response**
```C:\...\Error.php:31:
object(Rollbar\Response)[240]
  private 'status' => int 0
  private 'info' => null
  private 'uuid' => string '76439534-ab29-4821-8bd8-198fe84efbbe' (length=36)

C:\...\Error.php:31:string 'Status: 0
Body: null
URL: ' (length=26)
```

What is wrong here?
I've also tried to send a string instead of $exception, but it generates the same response.

Thanks in advance!

**Comment by ArturMoczulski** [comment]
Can you show what's in your `$rollbarInit`? Just scrub sensitive information before posting.

**Comment by jeliasson** [comment]
Sorry for keep you waiting. I had not a chance to test in the environment up until now. 

```php
$rollbarInit = array(
    'access_token' => $config->token->server,
    'environment' => !is_null(APPLICATION_ENV) ? APPLICATION_ENV : 'Undefined'
);

// Populate with Person information if user is logged in
if (MyProject_Person::getId()) {
    $rollbarInit['person'] = [
        'id' => MyProject_Person::getId(),
        'username' => MyProject_Person::getEmail(),
        'email' => MyProject_Person::getEmail()
    ];
}

var_dump($rollbarInit);
die;
```

**Result**
```php
array (size=2)
  'access_token' => string '54405cc6959748128fa5cd4674dXXXXX' (length=32)
  'environment' => string 'development' (length=11)
```

**Comment by coryvirok** [comment]
Looks like the error is being ignored via the `checkIgnore()` function in Config.js. The response you're seeing is likely from here: https://github.com/rollbar/rollbar-php/blob/14598997951469d8a0df51cc0849a79f1a1c1a89/src/RollbarLogger.php#L48

Check to make sure you don't have error reporting disabled. This code would cause the exception to be ignored in that case: https://github.com/rollbar/rollbar-php/blob/14598997951469d8a0df51cc0849a79f1a1c1a89/src/Config.php#L408

**Comment by jeliasson** [comment]
Any idea what causing me to end up there? Error reporting is not disabled on the development environment, 

```php
var_dump(error_reporting());
```
**Result**
```php
C:\...\Error.php:34:int 32767
```

**Comment by rokob** [comment]
I've noticed status 0 for both things that are ignored, but also when the server cannot be reached, either due to some network configuration or just the connection being down.

**Comment by jeliasson** [comment]
I can assure that we have connectivity and not utilizing any proxies. Anyone have any recommendations on how we can advance on this issue? Thanks!

**Comment by rokob** [comment]
As far as I can tell, there are legitimate scenarios where there is a status code of 0 being returned, e.g. one of the dummy responses due to checkIgnore functions or not being enabled, or having poor connectivity. Are there other scenarios? And if so, is it true that the data is not making it to Rollbar?

**Comment by jeliasson** [comment]
I have tested this from both my local internet connection, and the production version running in Microsoft Azure. I this that rules out poor connectivity- From what I've seen, the data is not reaching Rollbar at all.
Toughts on how to investigate further in this? Thanks!

**Comment by paullaffitte** [comment]
I have a similar issue. The log function return me this object :
```
private 'status' => int 0,
private 'info' => string 'Ignored' (length=7),
private 'uuid' => null
```
I have one application with two distincts environments (front-office and back-office). It happens only on the back-office.

**Comment by ArturMoczulski** [comment]
@paullaffitte The `Ignored` response is only returned in three cases:
1. There is a `checkIgnore` configuration set.
2. The log message is set to level that is below Rollbar's configured `minimumLevel`.
3. There is a filter applied and it's `shouldSend` method returns true-y value.

Can you check all of those three and make sure this doesn't happen in the case of your back-office?

**Comment by ArturMoczulski** [comment]
@jeliasson @paullaffitte 
Can you please try to upgrade to the latest `rollbar-php` and try to reproduce?
