### ISSUE TITLE
add nonce verification when processing $_POST

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php#202]
This is a security loophole Codacy brought to my attention:
![image](https://user-images.githubusercontent.com/2106631/27015820-0e7362ee-4ecd-11e7-875a-059e9492825c.png)

It's not an emergency, but we should look if lack of nonce verification exposes any danger of CSRF attacks and if so, how to prevent this.

**Comment by rokob** [comment]
I don't think this is an issue. We are using that setPost to store the data as context for an error, we are not actually sending this request.

**Comment by ArturMoczulski** [comment]
Cool. In that case I'll just annotate this to not be ignored by PHP MD
