### ISSUE TITLE
Rollbar erroneously throws "Invalid log level 'notice'" exception

### ISSUE THREAD

**Issue by PatchRanger** [rollbar/rollbar-php#212]
### Problem
I've added Rolllbar to my application as Monolog handler. It keeps throwing "Invalid log level 'notice'" exception.

### Reason
PSR-3 says:
> The LoggerInterface exposes eight methods to write logs to the eight RFC 5424 levels (debug, info, notice, warning, error, critical, alert, emergency).

While Rollbar doesn't seem to support `notice`.

### Solution
We should add `notice` level in order to complain PSR-3.

**Comment by PatchRanger** [comment]
Looks fixed in the latest dev: https://github.com/rollbar/rollbar-php/commit/e5cb998feacef078bf98aa4375cb4748ca01acfc . Please release as a new stable version.

**Comment by rokob** [comment]
Released v1.2.0
