### ISSUE TITLE
Exception level 'alert' not working when using Whoops exception handler

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar-php#218]
Whoops and Rollbar cannot coexist as error/exception handlers, so used Whoops as the primary exception handler.

The plan was: inside Whoops custom handler, log the error with Monolog, and then add the Rollbar handler so the same error theoretically should go to Rollbar. Some test exceptions were injected in our controllers' code. The exception message was not logged to Rollbar - the error reported was a Rollbar exception that said something like "alert is not a valid PSR log level".

Using Rollbar::log(Level::error(), $e) is working fine.

**Comment by rokob** [comment]
https://github.com/rollbar/rollbar-php/commit/e5cb998feacef078bf98aa4375cb4748ca01acfc added the alert level, plus some others that were missing for PSR 3 compliance. That is in the v1.2.0 release.
