### ISSUE TITLE
Sorry but calling exec() on production????

### ISSUE THREAD

**Issue by cordoval** [rollbar/rollbar-php#220]
Can we have a configurable way of getting rid of this optionally if you want, the sha1 can be passed via env var but way different not assuming you have git installed even on deploy

``` php
private static function getGitBranch()
    {
        try {
            exec('git rev-parse --abbrev-ref HEAD 2> /dev/null', $output);
            if ($output) {
                return $output[0];
            }
            return null;
        } catch (\Exception $e) {
            return null;
        }
    }
```

**Comment by rokob** [comment]
Yeah these git calls seemed a bit heavy to me as well, they are also a bit troubling from a performance perspective. It's a good idea to make it at least configurable to be optional.
