### ISSUE TITLE
README.md rollbar.js docs incorrect?

### ISSUE THREAD

**Issue by ytn3rd** [rollbar/rollbar-php#221]
The readme [says](https://github.com/rollbar/rollbar-php/tree/2af8e2d73b0763a02a50cd8f8bd2b857dab1cc8d#integration-with-rollbarjs) that we can setup rollbar.js like so,

```
$rollbarJs = Rollbar\RollbarJsHelper::buildJs(
    array(
        "accessToken" => "POST_CLIENT_ITEM_ACCESS_TOKEN",
        "captureUncaught" => true,
        "payload" => array(
            "environment" => "production"
        ),
        /* other configuration you want to pass to RollbarJS */
    )
);
```

I kept getting unauthorised access tough. Looking at the [source](https://github.com/rollbar/rollbar-php/blob/2af8e2d73b0763a02a50cd8f8bd2b857dab1cc8d/src/RollbarJsHelper.php#L59) it uses the options key in $config, not $config itself. Updating the above example to counter for this.

```
$rollbarJs = Rollbar\RollbarJsHelper::buildJs(
    array(
        'options' => array(
            "accessToken" => "POST_CLIENT_ITEM_ACCESS_TOKEN",
            "captureUncaught" => true,
            "payload" => array(
                "environment" => "production"
            ),
            /* other configuration you want to pass to RollbarJS */
        )
    )
);
```

appears to fix it. Just curious if updating the readme was overlooked, or if the RollbarJsHelper is incorrect.

**Comment by rokob** [comment]
Um yes that appears to be a bug in the documentation. I'm not sure why we use the options key for the configuration. I think the fix would be to just use the passed in config and leave the docs the way they are.

**Comment by ytn3rd** [comment]
Am going to throw through a few PRs today so Ill fix that.
