### ISSUE TITLE
Allow custom JS addition in RollbarJsHelper

### ISSUE THREAD

**Issue by Guite** [rollbar/rollbar-php#225]
It would be nice if there was a parameter for passing additional JavaScript code to the `RollbarJsHelper#buildJs()` method. This would be particularly useful for `Rollbar.global` and `Rollbar.configure` calls.

Because of a problem in IE9 (see https://github.com/rollbar/rollbar.js/issues/189) these must not be added in a separate `script` tag.

My current workaround is something like this:

```php
$rollbarJs = RollbarJsHelper::buildJs(...);
$rollbarJs = str_replace('</script>', '', $rollbarJs);
$rollbarJs .= "\n";
$rollbarJs .= "some Rollbar calls";
$rollbarJs .= '</script>' . "\n";
```

**Comment by cordoval** [comment]
@Guite correct me if i am wrong, a better option maybe it is to use the regular js and not the helper? The helper sounds a way to just configure the js when not used fully? am i wrong? If not then this helper is just like an example.

**Comment by ArturMoczulski** [comment]
@cordoval you're making a good point, but I don't see a problem with supporting both ways, especially if it would make things easier for @Guite

**Comment by ArturMoczulski** [comment]
Ready for review in PR https://github.com/rollbar/rollbar-php/pull/235

**Comment by Guite** [comment]
@cordoval There is a huge benefit from using the helper: I don't need to create additional copies of the JS code I need to maintain myself. This way I only have to update rollbar-php instead of having to care for rollbar.js, too. Also the helper has been added to rollbar-php anyway so we should look for making it applicable for many use cases.

@ArturMoczulski Looks good, thanks!

**Comment by cordoval** [comment]
@Guite i think you have not seen the default way of doing it with yarn and requiring the package.
But i won't stop you from doing it. It is good helper for people that want to do that.
