### ISSUE TITLE
Update rollbar.js code snippet

### ISSUE THREAD

**Issue by Guite** [rollbar/rollbar-php#226]
Currently https://github.com/rollbar/rollbar-php/blob/master/data/rollbar.snippet.js includes version 1.9.4 of rollbar.js. The most recent version is 2.1.0 though as shown in https://github.com/rollbar/rollbar.js/releases

Maybe think about a way to specify the desired version or semi-automate the update...

**Comment by ArturMoczulski** [comment]
This is a good place to figure out the process for automating rollbar.js updates.

**Comment by ytn3rd** [comment]
I don't like the idea of the JS code automatically updating because the php code detected a new version, but rather when you deploy rollbar-php it will have a set version of the rollbar.js version. At least then when you test it on a staging server and it works, you know its not going to suddenly break tomorrow because there was a breaking change in the JS that was updated.

Is it possible to have the CI drag in latest released rollbar.js for releases of rollbar-php?

**Comment by ArturMoczulski** [comment]
Ready for review in https://github.com/rollbar/rollbar-php/pull/228

**Comment by ytn3rd** [comment]
Learning more about composer every day, that is heaps better than the silly things I was thinking of!

**Comment by ArturMoczulski** [comment]
Just to clarify, you would like to be able to specify what version of rollbar.js you want to pull in rather than have the PHP SDK pull in the latest by default, is that correct?

**Comment by ytn3rd** [comment]
@ArturMoczulski , not lock to a specific version. My idea was to file_get_contents on a URL to drag latest copy down and save it locally. I didn't like the idea of testing my code and having it work and then having the system auto-update and it breaks. 

Having the rollbar.js as a dependency in composer is a lot better. It means that when I update my packages and test it al, thats where it will be locked at until I update my packages again.

**Comment by ytn3rd** [comment]
Is it possible to set a dependency of roller.js as something like >=1.9.4 or something so it can use anywhere from 1.9.4 to current master, and then if someone wants to stick with 1.9.4 they can add roller.js dependency in their composer manually before rollbar-php so if they want to lock to lower versions they can, if they want master automatically they can.

**Comment by cordoval** [comment]
we should just set some hook to compile this and plug it, no need to stain the composer.json please 👎

**Comment by rokob** [comment]
Including the entire rollbar.js project for just a single small file is untenable. We don't need to auto update the file, just having a script that grabs the snippet when we do a release is good enough.
