### ISSUE TITLE
Make fluentd a suggest requirement rather than mandatory

### ISSUE THREAD

**Issue by cordoval** [rollbar/rollbar-php#229]

**Comment by ArturMoczulski** [comment]
What's the reasoning behind making this change? @rokob @coryvirok what do you guys think?

**Comment by brianr** [comment]
@cordoval's suggestion sounds like the right thing to do to me. Most people using rollbar-php aren't going to use the fluent connector, so there's no reason it should be a required dependency.

**Comment by cordoval** [comment]
The way this works also is i use kubernetes and I have to have the freedom to just channel the exceptions however we wanted. Fluentd is not bad, just not a must have.

**Comment by ArturMoczulski** [comment]
Ready for review in PR https://github.com/rollbar/rollbar-php/pull/230

**Comment by cordoval** [comment]
closing this as #230 is LGTM too 👍
