### ISSUE TITLE
 Encryption for HIPAA

### ISSUE THREAD

**Issue by cordoval** [rollbar/rollbar-php#233]
I am trying to see from the client how the encryption is being done according to the document here:

https://cdn.rollbar.com/assets/shared/resources/compliance.pdf

i fail to find where, so we can enable it on our end?

or is there no support yet for this client to plug the key per project?

**Comment by coryvirok** [comment]
Hi @cordoval,

Our SDKs encrypt your data while in transit from your machines to ours using HTTPS. Once it reaches one of our machines we encrypt it before writing it to disk. So, all of the encryption of the data at rest is done within our datacenters so you don't have to worry about configuring anything on your end.

If you'd like to enable encryption for your Rollbar account, someone from our team can help you with that. Just send us an email support@rollbar.com and we'll get you started.

**Comment by cordoval** [comment]
Thanks @coryvirok
