### ISSUE TITLE
Error Duplication

### ISSUE THREAD

**Issue by bretto36** [rollbar/rollbar-php#236]
Hi All

Having some issues with this, everytime an Exception is thrown i get 2 items appear in rollbar. See below. How do i make it so only 1 error is thrown

#3632 E_ERROR: Uncaught Exception:: Uncaught Exception: Call to undefined method: 
#3645 Exception: Call to undefined method: 

\Rollbar\Rollbar::init(array(
                'access_token' => 'a3c1d64d84574031ae664a84622c0608',
                'environment' => (isset($_SERVER['environment']) && 'prod' == $_SERVER['environment'] ? 'production' : 'development'),
                'error_sample_rates' => array(
                    E_ERROR => 1,
                    E_WARNING => 0,
                    E_PARSE => 1,
                    E_NOTICE => 0.001,
                    E_CORE_ERROR => 1,
                    E_CORE_WARNING => 0,
                    E_COMPILE_ERROR => 1,
                    E_COMPILE_WARNING => 0,
                    E_USER_ERROR => 1,
                    E_USER_WARNING => 0,
                    E_USER_NOTICE => 0,
                    E_STRICT => 0,
                    E_RECOVERABLE_ERROR => 1,
                    E_DEPRECATED => 0,
                    E_USER_DEPRECATED => 0,
                )
            ));

**Comment by ArturMoczulski** [comment]
Ready for review in PR https://github.com/rollbar/rollbar-php/pull/240
