### ISSUE TITLE
"invalid or missing instance" error

### ISSUE THREAD

**Issue by Mattnmoore** [rollbar/rollbar-php#237]
I recently upgraded to the latest version, and I started getting this error when I try to send anything to Rollbar. 

```

Response {#85 ▼
  -status: 400
  -info: array:2 [▼
    "err" => 1
    "message" => "invalid or missing instance"
  ]
  -uuid: "a31624be-0fa6-4bb4-b0f9-f653c956f627"
}
```

```
use Rollbar\Rollbar;
use Rollbar\Payload\Level;

$config = [
    'access_token' => '[removed]',
    'environment' => 'local'
];

Rollbar::init($config);

$response = Rollbar::log(
    Level::INFO,
    'test'
);
```

**Comment by Mattnmoore** [comment]
It does seem like I can get requests to send correctly if there's no session data, but on the old version it sent our session data without any issues. Are there any constraints or reserved session indices that we need to take into consideration?

**Comment by rokob** [comment]
There has to be something else going on, that error message means that a payload was sent without a data key. I copied that code into a file and ran it even after setting something in $_SESSION. What is in your session when it fails?

**Comment by ArturMoczulski** [comment]
@Mattnmoore can you provide a dump of your session data as per @rokob request so we can investigate further?

**Comment by Mattnmoore** [comment]
It's a legacy application and there is a huge amount of data that gets stored in the session. There is a key of "instance". Could that be screwing something up? It's interesting because the old version didn't have this issue, even with the same session data.

**Comment by ArturMoczulski** [comment]
@Mattnmoore I just tried to reproduce the issue and used an `instance` key in the `$_SESSION` global. No success :( @rokob Do you think we can look into what's happening there when the request is processed by the Rollbar service that's produces the `invalid or missing instance` for @Mattnmoore requests?

**Comment by Mattnmoore** [comment]
If nothing else, I could start scrubbing the keys one by one before I call Rollbar. I was just curious if there was something obvious I was missing, or if it was a potential bug. Thanks for your guys' help!
