### ISSUE TITLE
class names in stack trace frames

### ISSUE THREAD

**Issue by mathroc** [rollbar/rollbar-php#243]
it would be nice to display the class name of the method calls in the stack trace frames

in Symfony, in production the classes are compiled into one big file so the file name is not helpful and only the method name is not enough.

you might want to take a look at how it’s done in symfony : 
![screenshot-2017-8-2 notice undefined variable zone 500 internal server error](https://user-images.githubusercontent.com/291531/28874956-3098b3a2-7794-11e7-84a5-860f63cf8404.png)

or whoops : 
![687474703a2f2f692e696d6775722e636f6d2f78695a317455552e706e67](https://user-images.githubusercontent.com/291531/28875211-0bccc562-7795-11e7-932f-56d9dc2db320.png)

**Comment by ArturMoczulski** [comment]
Ready for review in PR https://github.com/rollbar/rollbar-php/pull/245
