### ISSUE TITLE
Level::fromName not existing anymore

### ISSUE THREAD

**Issue by matjack1** [rollbar/rollbar-php#244]
Hello,

I've noticed that the public method `Level::fromName` is not existing anymore, is that intentional? Now the `__callStatic` method in the `Level` class is also picking up the calls to fromName and obviously break.

Would you like to reimplement `fromName` in `Level` or it was intentionally removed?

**Comment by ArturMoczulski** [comment]
This was intentionally removed. baibaratsky/yii-rollbar should be updated.
