### ISSUE TITLE
Show data for PUT requests in rollbar-php

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-php#248]
Details in https://app.clubhouse.io/rollbar/story/20293/show-data-for-put-requests-in-rollbar-php

**Comment by rokob** [comment]
There was a user report of an item that occurred during a PUT request with a POST body and that the body of the request was not included in the payload. This was using 0.18.2. I think that since 1.0 we have been including the POST body in the payload, but just double check that before closing this.

**Comment by ArturMoczulski** [comment]
This is ready for review in PR https://github.com/rollbar/rollbar-php/pull/266

Note: POST fields are only going to be included if Rollbar is configured with `include_raw_request_body`
