### ISSUE TITLE
RollbarNotifier class is missing in Monolog handlers folder

### ISSUE THREAD

**Issue by jianzhong** [rollbar/rollbar-php#249]
In monolog/src/Monolog/Handler/RollbarHandler.php, the class is trying to use a non-existing class 'RollbarNotifier' as the first parameter in the constructor. This causes PHP fatal error in my Symfony application. Our Rollbar upgrade failed due to this issue.

**Comment by jianzhong** [comment]
I've made a further investigation on the issue. The issue happened when I was trying to upgrade Rollbar from 0.18.2 to a later version by doing `composer require ~1.1`. The error was something like:
> PHP Fatal error:  Uncaught Error: Class 'RollbarNotifier' not found in ......

I noticed some changes in the autoload_psr4.php file under vendor\composer folder. The line 

> 'Rollbar\\' => array($vendorDir . '/rollbar/rollbar/src'),

becomes 

> 'RollbarNotifier\\' => array($vendorDir . '/rollbar/rollbar/src'),

If I changed RollbarNotifier to Rollbar, then I got another error in my Symfony application:

> PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "RollbarNotifier" from the global namespace.

**Comment by ArturMoczulski** [comment]
This is ready for Monolog's team review in the following PR https://github.com/Seldaek/monolog/pull/1042

**Comment by ArturMoczulski** [comment]
When this is finally merged into the Monolog package, remove `Note` sections from `rollbar/rollbar-php` and `rollbar/rollbar-php-examples` READMEs.

**Comment by ArturMoczulski** [comment]
It doesn't look like our PR for `Seldaek:monolog` is going to get merged anytime soon. In meantime, I included `Rollbar\Monolog\Handler\RollbarHandler` in our repo. Please, use `rollbar/rollbar-php:master` or wait until tag `v1.4.1`.

**Comment by letaniaferreira** [comment]
https://github.com/rollbar/rollbar-php-laravel/issues/93
