### ISSUE TITLE
Wordpress support

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-php#251]
Details in https://app.clubhouse.io/rollbar/story/1204/wordpress-support

**Comment by rokob** [comment]
Some type of first class plugin for wordpress for capturing JS and PHP errors and sending them to Rollbar. There is a community plugin: https://github.com/digitalmedia/rollbar

We may want to point to the community one, or we may want to fork it and make it better, or we may want to start from scratch. Possibly leveraging this notifier to do most of the work would be ideal.

**Comment by matthistuff** [comment]
Not sure what is mentioned in the clubhouse story but I am intrigued to know what is special about supporting WordPress. We have been using a custom WP plugin using rollbar-php and rollbar.js for quite some time now. Settings up WordPress specifics is actually not much work, around 100 lines in total.

**Comment by ArturMoczulski** [comment]
I found three community plugins:
https://github.com/digitalmedia/rollbar
https://github.com/flowdee/rollbar
https://wordpress.org/plugins/rollbar-logging/

All of them seem to be outdated and the latest supported version of Rollbar is v0.18.2

Out of those it seems to me that https://github.com/flowdee/rollbar is the best so I will use it to fork a new repo, fix up whatever is glitching and update to support the latest notifier version.

**Comment by ArturMoczulski** [comment]
I forked https://github.com/rollbar/rollbar-php-wordpress
Further issues regarding getting the Wordpress plugin up to speed will be continued as part of that project.
