### ISSUE TITLE
Rollbar Exception Logging ignores File and Line on Exception itself

### ISSUE THREAD

**Issue by kaikiai** [rollbar/rollbar-php#254]
Dear Rollbar Team,

when logging an Exception the Trace Information is solely taken from $Exception->getTrace().
Our Problem is, that this Information doesn't hold the actual File and Line where the Exception was thrown.
This is only found in the getLine and getFile named Methods on the Exception itself.

In http://php.net/manual/de/exception.gettrace.php this was also stated in an 5 years old comment.

We could get the correct Trace when adding to DataBuilder.php after Line 465 in Method makeFrames after reversing the frames array the following methods:

```
        $frame = new Frame($exception->getFile());
        $frame->setLineno($exception->getLine());
        $frames[] = $frame;
```

This is naturally not a solution for us, because it needs changes on the Rollbar Files, which come from composer in our Setup.

Now we are slightly confused, why we are seemingly the only one facing this problem, because we can't find any change on Exception Trace Handling in PHP while googling this problem.

Is this actually an problem in RollbarPHP? Or what is the correct way handling exceptions with RollbarPhp?

We use this to Log the Exception in an Custom Exception Handler (the standard Rollbar one can't catch Exceptions in Zend MVC Controllers) with following Code:
`Rollbar::log(Level::ERROR,$exception);
`
Composer installed following Rollbar Version:
`        "rollbar/rollbar": "^1.3"
`
and we use PHP 7 with Zend Framework 3 on Top

**Comment by gr8bit** [comment]
+1 for examples for correct Zend Framework integration! :)

**Comment by ArturMoczulski** [comment]
This is ready for review in PR https://github.com/rollbar/rollbar-php/pull/257

Also, turns out that function name information is acting funky makes for a very confusing stack trace. This will be addressed in a separate PR.

**Comment by rokob** [comment]
Merged, will be included in next release
