### ISSUE TITLE
Research OxCom/symfony3-rollbar-bundle as candidate for the official symfony 3 support repo

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php#270]
There is a need to provide quality support for Symfony3. Below repo looks like a good start but needs a lot of love.

https://github.com/OxCom/symfony3-rollbar-bundle

**Comment by rivkahstandig3636** [comment]
Closing this issue as there has already been work on this issue in another repo https://github.com/rollbar/rollbar-php-symfony3-bundle
