### ISSUE TITLE
fluent/logger

### ISSUE THREAD

**Issue by elazar** [rollbar/rollbar-php#277]
Why is `fluent/logger` both a [required](https://github.com/rollbar/rollbar-php/blob/ba5b945b90777f5acc1231898b6d7d18bc0d2d5d/composer.json#L36) and [suggested](https://github.com/rollbar/rollbar-php/blob/ba5b945b90777f5acc1231898b6d7d18bc0d2d5d/composer.json#L51) dependency? It doesn't look like it should be required. It was added as a required dependency in the `rollbar/rollbar` [1.2 release](https://packagist.org/packages/rollbar/rollbar#v1.2.0).

The [Packagist page](https://packagist.org/packages/fluent/logger) for `fluent/logger` references a [GitHub repository](https://github.com/fluent/fluent-logger-php) that [appears to no longer exist](https://twitter.com/elazar/status/923952401350094848). This is causing any new installations of `rollbar/rollbar` to fail.

```
- Installing fluent/logger (v1.0.1): Downloading    Failed to download fluent/logger from dist: The "https://api.github.com/repos/fluent/fluent-logger-php/zipball/c5a19ba8eb5e15f9ade72afeffba6b6e7eb51155" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing fluent/logger (v1.0.1): Cloning c5a19ba8eb

  [RuntimeException]                                                                                   
  Failed to clone https://github.com/fluent/fluent-logger-php.git via https, ssh protocols, aborting.  
  - https://github.com/fluent/fluent-logger-php.git                                                    
    Cloning into '/src/vendor/fluent/logger'...                                                        
    remote: Invalid username or password.                                                              
    fatal: Authentication failed for 'https://github.com/fluent/fluent-logger-php.git/'                
  - git@github.com:fluent/fluent-logger-php.git                                                        
    Cloning into '/src/vendor/fluent/logger'...                                                        
    ERROR: Repository not found.                                                                       
    fatal: Could not read from remote repository.                                                      
                                                                                                       
    Please make sure you have the correct access rights                                                
    and the repository exists.
```

**Comment by DrewSpace** [comment]
I am also having issues due to this problem :(

**Comment by rokob** [comment]
Aha yes it should not be required, it was moved to only suggested, but in a bad revert made it's way back in to required. I'll fix this.

**Comment by elazar** [comment]
@rokob Can we expect a 1.3.3 release shortly?

**Comment by elazar** [comment]
@rokob [There it is](https://github.com/rollbar/rollbar-php/releases/tag/v1.3.3). Thank you for the quick turn-around! ❤️

**Comment by rokob** [comment]
👍

**Comment by brycethornton** [comment]
Is there any reason to leave it in the suggested list? The repo doesn't seem to exist anymore.

**Comment by rokob** [comment]
That is weird, I don't know what happened to it. Let us figure out if it is a thing anymore, and if not then we can remove all of the fluent code too.
