### ISSUE TITLE
utf8 strings from php not being handled correctly

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-php#287]
See https://app.clubhouse.io/rollbar/story/21969/utf8-strings-from-php-not-being-handled-correctly and https://app.intercom.io/a/apps/rlisg82q/respond/inbox/conversation/9585083093 for details.

**Comment by ArturMoczulski** [comment]
I wasn't able to reproduce this issue anymore. It might have gotten fixed since then.
