### ISSUE TITLE
"src/Defaults.php detected as a virus" is still not fixed

### ISSUE THREAD

**Issue by tbopec** [rollbar/rollbar-php#290]
Hello,

As a follow up issue for [https://github.com/rollbar/rollbar-php/issues/269](issue-269).

The latest version of Avast with fresh virus signatures still detects src/Defaults.php as a virus.

Replacing of usage of exec function to shell_exec fixes this issue:

```
            if (function_exists('shell_exec')) {
                $output = trim(shell_exec('git rev-parse --verify HEAD 2> /dev/null'));
                if ($output) {
                    return $output;
                }
            }
```

Please have a look here

Best wishes,
Pavel

**Comment by ArturMoczulski** [comment]
This is ready for review here: https://github.com/rollbar/rollbar-php/pull/291
