### ISSUE TITLE
Error duplication for non generic exceptions

### ISSUE THREAD

**Issue by ftrrtf** [rollbar/rollbar-php#293]
@ArturMoczulski hi, I guess condition (from MR https://github.com/rollbar/rollbar-php/pull/240)
`strpos($last_error['message'], 'Uncaught exception') === 0` should be replaced by `strpos($last_error['message'], 'Uncaught') === 0` (allowed types of exception is checked on the line above).

Because for now only generic exceptions will be skipped by the condition on fatal handler, and `MyException` will be logged one more time. 

We are experiencing such issue with each symfony/php7 app (have not tested with other environments), when even fatals are exceptions, plus wrapped by symfony stuff, like: 
`Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Call to a member function getId() on null in /var/www/...`

**Comment by ArturMoczulski** [comment]
This is resolved in PR https://github.com/rollbar/rollbar-php/pull/295
