### ISSUE TITLE
Missing tag on last master

### ISSUE THREAD

**Issue by tbopec** [rollbar/rollbar-php#294]
Hello, @ArturMoczulski !

You fixed the issue github-290, but this improvement is still not released with tag/version.

When is it planned to have a release v1.3.6?

Best wishes,
Pavel

**Comment by ArturMoczulski** [comment]
Hey @tbopec 

This is now available in tag v1.3.6:
https://github.com/rollbar/rollbar-php/tree/v1.3.6

Let me know if you have any questions
