### ISSUE TITLE
Add config option to enable/disable

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar-php#297]
Can we add a configuration option to easily turn on and off the integration? The idea is to be able to disable Rollbar without having to change or comment out code. Similar to rollbar.js's: 
https://github.com/rollbar/rollbar.js#disable-reporting-to-rollbarcom

**Comment by nicogranelli** [comment]
+1

**Comment by ArturMoczulski** [comment]
This is ready for review in PR https://github.com/rollbar/rollbar-php/pull/300
