### ISSUE TITLE
Not Working with New Relic agent

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-php#309]
[USER]:

Trying to set up Rollbar PHP client and New Relic agent.

New Relic agent stops tracking application performance, but works again when Rollbar PHP is removed.

internal: https://app.intercom.io/a/apps/rlisg82q/respond/inbox/488687/conversations/14332615800

**Comment by ArturMoczulski** [comment]
I set up a project with New Relic and Rollbar but I wasn't able to reproduce the problem. I need more details on what exactly is happening.

I'm working on making the SDK more verbose right now here: https://github.com/rollbar/rollbar-php/issues/312

Once I add more debugging info, let's try to find out what exactly is happening.

**Comment by LawnGnome** [comment]
I attacked this today too from the New Relic side, and I haven't been able to reproduce the issue either. I'll let you know if I find anything!

**Comment by theUniC** [comment]
Hi! I was the one that reported it some days ago. If helps I can attach our new-relic / php config.

**Comment by ArturMoczulski** [comment]
@theUniC that would be awesome. Also, I just merged into `master`  a new configuration option that will let you get more details on what's happening inside the SDK. So,

1. Switch to using `rollbar/rollbar-php:master` instead of the last tag `v1.3.6`. 
2. Configure your Rollbar with
```php
'verbosity' => \Psr\Log\LogLevel::DEBUG
```
3. Post the contents of your `/tmp/rollbar.debug.log`.

You can find more about the `verbosity` config option here: https://github.com/rollbar/rollbar-php

**Comment by ArturMoczulski** [comment]
@theUniC Any more details on this?

**Comment by theUniC** [comment]
@ArturMoczulski It's a New Relic issue. We investigated it alongside them and found out that by completely disabling error tracing on the newrelic-agent things were working out again. I suspect they are doing things internally when `register_shutdown_function` callbacks are invoked, but don't have any more information.

**Comment by ArturMoczulski** [comment]
I see. I'm going to close the issue here now.

However, you probably still need to fix this situation for yourself - I would love to hear what you guys come up with to have the New Relic agent work with Rollbar PHP SDK.
