### ISSUE TITLE
An exception does not show in the dashboard for PHP app

### ISSUE THREAD

**Issue by afa17** [rollbar/rollbar-php#311]
Hi Rollbar team,
I have a problem of receiving/ showing my messages on the Dashboard .
I am using my localhost for Moodle3.3 PHP application on XAMPP bundle. 

The Rollbar was activated with the following activation code:

`$config = array(
    'access_token' => 'ACCESS_TOKEN',
    'environment' => 'development'    
);
Rollbar::init($config);`

And I have thrown an error as follows:

`
Rollbar::log(Level::info(), 'Test info message');
throw new Exception('Test exception');`

It prints out on my screen as  - 

> Test info message

, BUT it does not show on my dashboard.
Note: I can ping to api.rollbar.com

Can you please help to display the errors on my dashboard.

Best regards,
AFA17

**Comment by afa17** [comment]
any updates on this issue guys?

**Comment by ArturMoczulski** [comment]
@afa17 thanks for reporting. I'm looking into this right now. In meantime, it would be awesome if you provide some more information.

I just added internal debugging information logging to the `master` branch. Do you think you can do the following:
1. Switch to using `rollbar/rollbar-php:master` instead of the latest tag `v1.3.6`. 
2. Set up your `Rollbar` configuration to use 
```php 
'verbosity' => \Psr\Log\LogLevel::DEBUG
```
3. Trigger `Rollbar::log` method.
4. Post the contents of you `/tmp/rollbar.debug.log` with scrubbed access token.

This will let me see exactly what is happening and what response you're getting from Rollbar API.

**Comment by afa17** [comment]
Hi Arthur,

Thanks for your reply.
I have cloned the tag v.1.4.0 & run steps 2 and 3.
Though I could not find rollbar.debug.log file.

Am I doing these steps correctly?
Thanks!
Best regards,
Muzaffar

use \Rollbar\Rollbar;
use \Rollbar\Payload\Level;

$config = array(
    'access_token' => '197baa6606164cd38b76792236762bd2',
    'environment' => 'development',
    'verbosity' => \Psr\Log\LogLevel::DEBUG
);
Rollbar::init($config);


Rollbar::log(Level::info(), 'Test info message! Hello 3 !');
throw new Exception('3. Test exception! Hello!');

try {
    throw new \Exception('test exception');
} catch (\Exception $e) {
    Rollbar::log(Level::ERROR, $e);
}

// Message at level 'info'
Rollbar::log(Level::INFO, 'testing info level');
Rollbar::log(Level::DEBUG, 'testing DEBUG level');

**Comment by afa17** [comment]
Any updates Artur ?

**Comment by ArturMoczulski** [comment]
@afa17 Can you verify that your `sys_get_temp_dir` resolves to `/tmp`? And if so, what are your permissions on that directory?

We need to get access to those debug logs.

**Comment by afa17** [comment]
@ArturMoczulski  Thanks for follow-up. I have checked that I can access the temp dir (\AppData\Local\Temp\rollbar.debug.log - my OS is windows 7) and I have all permissions. However,  the log file was not generated in that folder.

But I found the following error that can help us:
**Exception - logging with Rollbar failed. DEBUG Response = Status: 0 Body: "Ignored" URL:**

When I run the following code:
`$response = Rollbar::log(Level::DEBUG, 'DEBUG:testing wasSuccessful()');
if (!$response->wasSuccessful()) {
    throw new \Exception('logging with Rollbar failed. DEBUG Response = ' . $response);
}`

**Comment by afa17** [comment]
When I dump the $response variable, I got the following:
if (!$response->wasSuccessful()) {
    var_dump($response);
}

TEMP dir = C:\Users\Username~1\AppData\Local\Temp

object(Rollbar\Response)#66 (3) { 
	["status":"Rollbar\Response":private]=> int(0) 
	["info":"Rollbar\Response":private]=> string(7) "Ignored" 
	["uuid":"Rollbar\Response":private]=> NULL 
}

**Comment by afa17** [comment]
any updates Artur?

**Comment by ArturMoczulski** [comment]
@afa17 Thanks for your patience. Can you also post a dump of your request (after scraping sensitive info)?

**Comment by afa17** [comment]
@ArturMoczulski  I have attached the har file of the request to my localhost. If you need, tese are the header properties:
GET / HTTP/1.1
Host: localhost
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: http://localhost/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: Phpstorm-4b3599cd=c69c2ba5-5177-406e-bc41-c326d995f12b; 
Phpstorm-b316c6ac=46f84ae1-f31a-4d85-bfb6-be8fd33c4053; 
MoodleSession=8on72mmdb696e85o7lflhmv182

**Comment by ArturMoczulski** [comment]
Sorry @afa17 . I don't see it attached anywhere. I need the body of the request.

**Comment by ArturMoczulski** [comment]
@afa17 The file you attached doesn't seem to be a valid Rollbar API request. Are you sure this the content Rollbar SDK is sending? I suggest `var_dump` after this line https://github.com/rollbar/rollbar-php/blob/master/src/RollbarLogger.php#L105

like so
```php
$this->debugLogger->info(
                "Payload scrubbed and ready to send to ".
                $this->config->getSender()->toString()
            );
            $this->debugLogger->debug(json_encode($toSend, true));

var_dump($toSend);
            
            $response = $this->send($toSend, $accessToken);
```

**Comment by afa17** [comment]
@ArturMoczulski  THANKS! As I debugged it caught up at line 87 at RollbarLogger.php:
 if (!$this->levelFactory->isValidLevel($level)) {
            throw new \Psr\Log\InvalidArgumentException("Invalid log level '$level'.");
        }

**Comment by ArturMoczulski** [comment]
I'm closing the issue since there has been no reponse since March 13th.
