### ISSUE TITLE
ReadmeTest class doesn't pass the tests

### ISSUE THREAD

**Issue by gelige** [rollbar/rollbar-php#315]
Hi! 

Noticed #314 pull request fail and tested it locally.

`ReadmeTest::testBasicUsage()` and `ReadmeTest::testBasicUsage2()` methods' assertions pass fine when `ReadmeTest.php` runs alone, but fail when all tests run together.

It seems so that previous tests set `Rollup` static attributes that interfere with later usage.

**Comment by ArturMoczulski** [comment]
@gelige I removed the assertions, for now, to let the builds pass. I will resolve the failing assertions in the next tag.

**Comment by ArturMoczulski** [comment]
Fixed in https://github.com/rollbar/rollbar-php/pull/326
