### ISSUE TITLE
Error: Cannot access private property Rollbar\Rollbar::$logger

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-php#319]
internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/14730430660

User upgraded to the rollbar-php v1.4.0, but this error is still occurring. Here is the composer.lock for reference:

```"name": "rollbar/rollbar",
"version": "v1.4.0",
"source": {
"type": "git",
"url": "https://github.com/rollbar/rollbar-php.git",
},

**Comment by ArturMoczulski** [comment]
I'm not able to reproduce the problem. I will get in touch with the user to resolve the issue.

**Comment by ArturMoczulski** [comment]
Got in touch with the customer. Their production systems are working fine. The issue only occurs in the local environment for one of their devs. I'm in touch with him now but the issue here can be closed.
