### ISSUE TITLE
Post to https://api.rollbar.com/api/1/item/item/ correct?

### ISSUE THREAD

**Issue by niektenhoopen** [rollbar/rollbar-php#320]
My Rollbar error logging stopped working and by looking at the code I (might have) figured out what the problem might be. I debugged the curl request and found out that it posts to https://api.rollbar.com/api/1/item/item/  ("item" twice)

It looks weird to me because your docs have the word "item" only once. 

Is this correct and still functional behaviour? Your example code from the readme does not work (at my environment) at the moment.

It looks like it tries to find an error with the ID "item" because this is the response:
```
  "err": 1,
  "message": "not found"
```

It does work when I remove the last 'item/' from the URL. Any ideas? (Or did you maybe change the routing on your API URL?)

Potentially relevant code:

src/Senders/CurlSender.php:
```
class CurlSender implements SenderInterface
{
    private $utilities;
    private $endpoint = 'https://api.rollbar.com/api/1/item/';
```

src/Config.php:
```
    private function setTransportOptions(&$config)
    {
        if (array_key_exists('base_api_url', $config)) {
            $config['senderOptions']['endpoint'] = $config['base_api_url'] . 'item/';
        }

        if (array_key_exists('endpoint', $config)) {
            $config['senderOptions']['endpoint'] = $config['endpoint'] . 'item/';
        }

```

**Comment by rokob** [comment]
This is strange because the code would seem to have existed for many months that would lead to that and it is wrong.

**Comment by niektenhoopen** [comment]
@rokob I know. I suspect that the API accepted the payload at /item/item as well but maybe changed the routing? /item/([0-9]}) is for viewing an item (if I remember it correctly) and it looks like this might have changed to /item/(.*} ? (I am just trying to guess what could have caused the issue the occur after a long day of work)

**Comment by rokob** [comment]
Those code snippets are a red herring, the CurlSender `endpoint` variable does not get the `item/` appended to it. We only use that `endpoint` variable if one is not set in the configuration. Are you setting endpoint in your configuration?

**Comment by niektenhoopen** [comment]
Hmm. I was checking it as well. Seems like the https://github.com/baibaratsky/yii2-rollbar sets it:
```
public $baseApiUrl = 'https://api.rollbar.com/api/1/item/';
```

The baseApiUrl should not contain `item/`, right?

I am still wondering why this issue started to play up now, but it looks like it is not a Rollbar interruption.

**Comment by rokob** [comment]
Ah yes it should not contain `item/`. I agree it is weird that is just cropping up now, it could be what you are saying about the backend accepting that before and that changing recently.

**Comment by rokob** [comment]
https://github.com/baibaratsky/yii2-rollbar/commit/1561d6490a06ba27818ce6eef54bacf3d6abfc8f#diff-e6b436425177a2b2c600da9dd3760ef5 is where it got added so it could be due to an upgrade in versions.

**Comment by rokob** [comment]
I made https://github.com/baibaratsky/yii2-rollbar/pull/14 to fix it in that library

**Comment by niektenhoopen** [comment]
This issue does not need a solution (for me) anymore, but I am not sure if there are more people using item/item/ to post to. 

I only figured it out after I realised that I had no errors logged for the past 14 days and usually it logs about 1 error per week. The annoying thing is that if you are relying on Rollbar for error logging, and it is not working, people will probably incorrectly assume that everything is working flawlessly ;)

**Comment by niektenhoopen** [comment]
Feel free to close this one. I am not sure if you want to look into backend routing so I will just leave it up to you to close this one 😄 Thanks for the very quick response guys! (and teaching me about the "red herring", never heard that expression before 😄 )
