### ISSUE TITLE
Wordpress Plugin PHP Errors not being sent.

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-php#321]
I have a user who receives these two errors:

`#38 E_NOTICE: unserialize():: unserialize(): Error at offset 5 of 34 bytes`
`#37 E_NOTICE: Undefined index:: Undefined index: seq_ques`

from the wordpress rollbar plugin, but is unable to send any other PHP errors to Rollbar. Test messages and Javascript errors are sent through though.

config:

*status:* [x] PHP error logging [x] Javascript error logging
*access token:* his_access_token
*environment:* ________
*logging level:* Absolutely everything (E_ALL)

internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/14822225550

**Comment by rivkahstandig3636** [comment]
Moving this over to the wordpress plugin repo as this appears to be an issue with that notifier and not this one.
