### ISSUE TITLE
413 Payload Too Large

### ISSUE THREAD

**Issue by h0gar** [rollbar/rollbar-php#343]
Hi.

There was an issue with json encoding errors. See: https://github.com/rollbar/rollbar-php/issues/265

It's solved, but now I have another issue with rollbar-php. I have a script doing imports of large files.
When there is an error, rollbar sends the payload which includes the trace and the arguments, and these arguments contain large amont of data from the imported file.

As a result, rollbar returns a "413 Payload Too Large" http code.

How can I prevent rollbar-php from sending these heavy trace arguments so that the payload remains small enough?

**Comment by rivkahstandig3636** [comment]
We will take a look into this, sorry for the delay!

**Comment by adrian-enspired** [comment]
setting `local_vars_dump` to `true` prevents rollbar from sending function arguments along with the trace chain.  I recently had to figure that out as a temporary measure until [347](https://github.com/rollbar/rollbar-php/issues/347) is solved.

If you don't mind, how large is your payload when you get a 413 error?  We've been having some errors that don't make it to rollbar and can't figure out why; I thought maybe it had to do with size.

**Comment by h0gar** [comment]
Thanks, didn't know about "local_vars_dump".

I don't have a precise number, but it's at least several megabytes.

**Comment by iwex** [comment]
@ArturMoczulski why did you close it?
I think, the library should somehow understand what to send in this case, or use compression etc, because
`local_vars_dump=true` exists for some reason.

**Comment by ArturMoczulski** [comment]
@iwex sounds to me like the issue is resolved with `local_vars_dump=false` or am I missing something?

**Comment by iwex** [comment]
@ArturMoczulski I guess there should be some truncating strategy to remove local_vars_dump if the size of payload is too big.

**Comment by ArturMoczulski** [comment]
@iwex thank you for suggestions. I think both a truncation strategy specifically to deal with `local_vars_dump` can be a good idea as well as a notification in rollbar when the payload is too big. I'll look into those.

In meantime, you might get over a problem like this by setting `max_nesting_depth`

**Comment by amcsi** [comment]
For people to be able to find this in the future, what I saw in Rollbar as a result of this was:

```
Symfony\Component\Debug\Exception\FatalErrorException:
Uncaught ErrorException: Trying to access array offset on value of type null in /var/www/vendor/rollbar/rollbar/src/RollbarLogger.php:121
```

This was very cryptic to me, and there was nothing telling me that this was because of a `413` status code. I had to debug on production to find out.
