### ISSUE TITLE
PHP Interface, log() method isn't handling fingerprint as documented

### ISSUE THREAD

**Issue by chris-miller-jonah** [rollbar/rollbar-php#350]
https://docs.rollbar.com/docs/grouping-algorithm Shows that you should be able to pass an array as the third parameter to Rollbar::log(Level::INFO, "Some message", array("fingerprint"=>"my-custom-fingerprint")); and that it will be used for grouping purposes.

However when I pass a fingerprint value like that and then check on Rollbar, I see that the Item occurrences I created have the fingerprint showing up in the messages.fingerprint. And the occurrences I created that have unique fingerprints are still grouped under the same item, not under separate items as expected.

Is the documentation correct? Or is there another way I'm supposed to set the fingerprint when I call the log() method?

**Comment by rivkahstandig3636** [comment]
Thanks for pointing this out! We'll take a look.

**Comment by ArturMoczulski** [comment]
This needs to be investigated as part of the current milestone.

**Comment by ArturMoczulski** [comment]
Fixed in master and will be included in `v1.5.4`
