### ISSUE TITLE
Yii2 Custom Error Handler - Errors should not be displayed in browser

### ISSUE THREAD

**Issue by HenonoaH** [rollbar/rollbar-php#356]
I need to create a custom error handler by extending rollbar error handler that should always handle fatal errors, but handle notice errors only if we are in debug mode. In production mode, all notice errors should not be displayed in the browser instead it should be logged in rollbar and get notified. Can anyone suggest an idea on how to go with this error handling?

I just started by extending Yii2 base error handler,

```php
<?php
namespace common\components;
class ErrorHandler extends \yii\web\ErrorHandler
{
    public function register()
    {
        ini_set('display_errors', false);
        set_exception_handler([$this, 'handleException']);
        register_shutdown_function([$this, 'handleFatalError']);
    }
}
```

With this above code, I'm able to hide notice error from the browser and get logged in php error log. Now the thing is I need to get log in rollbar and get notified as usual.

**Comment by HenonoaH** [comment]
@rivkahstandig3636 @ArturMoczulski Do you get any findings on How to fix this?

**Comment by ArturMoczulski** [comment]
@HenonoaH initialize Rollbar as usual with `\Rollbar\Rollbar::init`. It will register additional error handler, exception handler and shutdown function that will take care of Rollbar logging.

Does it help?

**Comment by ArturMoczulski** [comment]
Closing the issue since there has not been any feedback since my last response. I'll reopen if this pops up again.

**Comment by HenonoaH** [comment]
Sorry, @ArturMoczulski I was late to share my findings. It got working just extending the base error handler. Thank You.
