### ISSUE TITLE
Undefined index 'access_token' when personFunc throws error

### ISSUE THREAD

**Issue by RDelorier** [rollbar/rollbar-php#359]
https://github.com/rollbar/rollbar-php/blob/0fe0b219b1c0f671701383aaf24eb605082c9027/src/DataBuilder.php#L861

Calling Rollbar::scope without an 'access_token' index in the config throws another error.

**Comment by ArturMoczulski** [comment]
@RDelorier I don't think I fully understand the problem here. Can you elaborate more?

**Comment by RDelorier** [comment]
We have some custom handlers throwing the exception but here is the trace. It happens when I cause an error in the `person_fn`.

![screen shot 2018-08-06 at 7 09 31 pm](https://user-images.githubusercontent.com/2295675/43745373-5b02667a-99ac-11e8-91f8-c0ba632a963e.png)

**Comment by RDelorier** [comment]
The catch below calls Rollbar::scope without an `access_token` which triggers the above.

![screen shot 2018-08-06 at 7 14 03 pm](https://user-images.githubusercontent.com/2295675/43745477-ebf1da08-99ac-11e8-8731-e3d300b1ab54.png)

**Comment by ArturMoczulski** [comment]
@RDelorier gotcha. I'll address this in the upcoming release

**Comment by JohnKendhammer** [comment]
I was not able to recreate this issue. I dived into the code and tried to cause an exception in the person_fn, but I am getting the access_token set properly. This makes me think that there may be something going on with the access_token after your configuration call.  Could you give me some more information on how your Rollbar is setup.

**Comment by ArturMoczulski** [comment]
I'm closing this for now due to lack of feedback. @RDelorier when you provide more context I will reopen
