### ISSUE TITLE
Decouple rollbar from monolog

### ISSUE THREAD

**Issue by rkrx** [rollbar/rollbar-php#360]
We use another PSR-3 compatible logger-implementation and rollbar enforces the monolog, which is an unnecessary in our case.

**Comment by ArturMoczulski** [comment]
Rollbar PHP supports Monolog but it's independent of it. I'm confident we can help you achieve what you need. Can you tell me more about the problem you're having?

**Comment by rkrx** [comment]
You have it in your [composer.json](https://github.com/rollbar/rollbar-php/blob/master/composer.json#L36). In that sense, you force a project to load monolog.

**Comment by ArturMoczulski** [comment]
I see what you mean. Yeah, we can drop that. Actually, it looks like Monolog maintainers finally took action on our pull request to update their included RollbarHandler, so the temporary solution for Monolog handler we had can be completely dropped.

This will be addressed as part of https://github.com/rollbar/rollbar-php/issues/380
