### ISSUE TITLE
Rollbar fails to get git branch if allow_exec false and no default set

### ISSUE THREAD

**Issue by emporium-nsalter** [rollbar/rollbar-php#374]
This bug was introduced in the 1.5.2 update with the refactoring of the Defaults class. This code in particular (src/Defaults:129): 

```
public function gitBranch($gitBranch = null, $allowExec = true)
    {
        if ($gitBranch) {
            return $gitBranch;
        }
        if (!isset($this->defaultGitBranch) && $allowExec) {
            $this->defaultGitBranch = self::getGitBranch();
        }
        return $this->defaultGitBranch;
    }
```

causes an E_NOTICE to be thrown by line 137 if `$allowExec` is false, as `defaultGitBranch` is never set. There are many cases where a default git branch makes no sense (production, non-git repo) and where exec should not be called. A simple fix would be to set a default value of empty string or 'none' to stop this happening in future.

**Comment by rivkahstandig3636** [comment]
Thanks for letting us know!
