### ISSUE TITLE
Mismatch between docs and implementation for 'check_ignore' option

### ISSUE THREAD

**Issue by Hoten** [rollbar/rollbar-php#376]
https://docs.rollbar.com/docs/php#section-configuration

> $exception: a RollbarException instance that will allow you to get the message or exception

```
$config = array(
        'access_token' => '...',
        'check_ignore' => function ($isUncaught, $exception, $payload) {
            if (isset($_SERVER['HTTP_USER_AGENT']) && strpos($_SERVER['HTTP_USER_AGENT'], 'Baiduspider') !== false) {
              // ignore baidu spider
              return true;
            }

            // no other ignores
            return false;
        };
    );
    Rollbar::init($config);
```

If you log a string:

```
Rollbar::logger()->log('warning', 'some error');
```

The value passed for `$exception` to the check_ignore function is a string, not a RollbarException. This creates an error if you do not do a type check before attempting to call methods on this object.

**Comment by rivkahstandig3636** [comment]
Thanks for letting us know!

**Comment by ArturMoczulski** [comment]
Fixed.
