### ISSUE TITLE
Truncate long strings in large payloads to respect 128kb limit

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar-php#38]
rollbar-gem does this: https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar.rb#L400-L410 . We should do something similar here.

**Comment by ArturMoczulski** [comment]
@brianr I need a bit more explanation on what needs to be done here:

- What parts of the payload should be truncated?
- The 128kb limit is a limit for the whole payload or single field of the payload?
- Can you provide an example of when such truncating should be done?

**Comment by ArturMoczulski** [comment]
Also, the rollbar-gem example you provided seems to not be up to date (lines 400-410 are not there anymore). Can you point me to where this resides now?

**Comment by coryvirok** [comment]
Here's a more up-to-date link - https://github.com/rollbar/rollbar-gem/tree/master/lib/rollbar/truncation

cc @rokob for direction on how to proceed with truncation.

**Comment by rokob** [comment]
The API will reject requests that are too large: https://rollbar.com/docs/api/items_post/#response-codes

> 413 | Request entity too large | Max payload size is 128kb. Try removing or truncating unnecessary large data included in the payload, like whole binary files or long strings.

The docs say 128kb, the reality is that the entire entity-body of the post request must be below 1MB. That is, the Content-Length as defined by: "Content-Length entity-header field indicates the size of the entity-body, in decimal number of OCTETs" must be less than 1MB.

What this means in practice is that if the payload itself is too large, we need to truncate some things to get it below the desired threshold. We want to truncate strings that are values in the request body (i.e. not keys in a JSON object).

The way the gem decides to do this, is to pick a max payload size of 0.5 MB (https://github.com/rollbar/rollbar-gem/blob/bf6d439be15455b557886fc73304ba00303aa278/lib/rollbar/truncation.rb#L12), and then to apply strategies in order until the payload satisfies this size limit: https://github.com/rollbar/rollbar-gem/blob/bf6d439be15455b557886fc73304ba00303aa278/lib/rollbar/truncation.rb#L22-L25

Those strategies https://github.com/rollbar/rollbar-gem/tree/bf6d439be15455b557886fc73304ba00303aa278/lib/rollbar/truncation start with some conservative truncations such as removing the middle of the stack trace if there are an excessive number of frames, and get more aggressive as the payload continues to be too large.

There is a bit of flexibility in how to do the truncation, but the main rules are:

1. Must be less than a given size (1MB for the whole entity-body, but we could be safe and make it 0.5 MB the way the gem does)
2. We want to remove as little information as possible, and the information we do remove should be non-essential for debugging purposes.

The strategies in the gem try to only remove data for very long strings or excessively large stack traces, and if that doesn't work, they truncate further.

**Comment by ArturMoczulski** [comment]
This sounds like it's going to take much longer than six hours I provided in the initial estimate

**Comment by rokob** [comment]
Merged
