### ISSUE TITLE
getUserIp looks at HTTP_X_FORWARDED_FOR then overwrites it anyway

### ISSUE THREAD

**Issue by zephod** [rollbar/rollbar-php#381]
https://github.com/rollbar/rollbar-php/blob/master/src/DataBuilder.php#L827

Just encountered this bug. This library appears to do something clever with `HTTP_X_FORWARDED_FOR` and with `HTTP_X_REAL_IP`, but line 827 overwrites it with `REMOTE_ADDR` no matter what. I'm not 100% sure what the intended behaviour is - the code linked above looks like a regression or a bad merge.

For now I am working around this by writing hacks in my code to overwrite REMOTE_ADDR with HTTP_X_FORWARDED_FOR to trick Rollbar into behaving nicely :)

**Comment by rivkahstandig3636** [comment]
Thanks for bringing this to our attention!

**Comment by ArturMoczulski** [comment]
Thanks @zephod We will get this addressed soon.

**Comment by ArturMoczulski** [comment]
This is now fixed in `master` and will be included in `v1.5.4`
