### ISSUE TITLE
Recursion exceeding xdebug.max_nesting_level

### ISSUE THREAD

**Issue by RDelorier** [rollbar/rollbar-php#383]
Classes with recursive references cause `serializeForRollbar` to exceed xdebug.max_nesting_level

https://github.com/rollbar/rollbar-php/blob/a934d2f009095b35559fb2c68b4f0b3a58d0dc5a/src/Utilities.php#L68

![screen shot 2018-06-27 at 1 07 39 pm](https://user-images.githubusercontent.com/2295675/41988755-1f9b5cec-7a0b-11e8-91dc-e86e1b485058.png)

**Comment by rivkahstandig3636** [comment]
Thanks for the report!

**Comment by ArturMoczulski** [comment]
@RDelorier can you help me with a particular example of a recursive reference that causes this for you?

**Comment by RDelorier** [comment]
@ArturMoczulski I can't seem to reproduce this right now, If you want to close the ticket then I can give more info if it happens again.

**Comment by ArturMoczulski** [comment]
@RDelorier thx. Let us know if you run into this problem again and I'll reopen
