### ISSUE TITLE
Undefined offset when when adding context

### ISSUE THREAD

**Issue by RDelorier** [rollbar/rollbar-php#384]
Undefined offset when $line = 0 should be set to `$line = max(0, $line - 1)` I think.

I got this error when max_nesting_level was reached in #383 

https://github.com/rollbar/rollbar-php/blob/a934d2f009095b35559fb2c68b4f0b3a58d0dc5a/src/DataBuilder.php#L493

![screen shot 2018-06-27 at 12 58 33 pm](https://user-images.githubusercontent.com/2295675/41989782-715346c8-7a0e-11e8-9321-10bf11792417.png)

**Comment by rivkahstandig3636** [comment]
Thank you for this report as well!

**Comment by ArturMoczulski** [comment]
Fixed
