### ISSUE TITLE
Truncation strategies do not truncate Frame objects

### ISSUE THREAD

**Issue by Hoten** [rollbar/rollbar-php#387]
The `Rollbar\Truncation\StringsStrategy` strategy won't trim large strings found in the Frame objects (so, if a very large string parameter is in a stack trace, it won't be trimmed). This has resulted in very large error payloads, and blocks the rollbar agent.

There's no way to provide custom truncation strategies, so I've gotten around this by applying a custom scrubber. I'll share that code here.

It would be nice if this were part of the default truncation strategy. As well, it would be nice if it were possible to provide custom truncation strategies. At the moment, they are hard coded.

----
example problem error:
```
function badfn($bigArg) {
    throw new \Exception('Big error thrown intentionally');
}

badfn(str_repeat('a', 15 * 1000 * 1000));
```

custom scrubber:

```
class RollbarScrubber extends \Rollbar\Scrubber
{
    public function scrub(&$data, $replacement = '********', $path = '')
    {
        $frames = $data['body']['trace']['frames'] ?? null;
        if ($frames) {
            $this->trimLongStrings($frames);
        }

        $data = parent::scrub($data, $replacement, $path);

        return $data;
    }

    // Rollbar's truncation strategy (StringsStrategy) does not trim Frames
    protected function trimLongStrings(&$data)
    {
        if (is_string($data) && strlen($data) > 10000) {
            // anything super big is surely not useful. trim it down to barely anything
            // use mb_ just in case the string is Unicode
            $data = mb_substr($data, 0, 100) . ' ... truncated';
        } else if (is_array($data)) {
            foreach ($data as &$value) {
                $this->trimLongStrings($value);
            }
        } else if ($data instanceof \Rollbar\Payload\Frame && $data->getArgs()) {
            $args = $data->getArgs();
            $this->trimLongStrings($args);
            $data->setArgs($args);
        } else if (is_object($data)) { // this may be a bad idea
            foreach (get_object_vars($data) as $key => &$value) {
                $this->trimLongStrings($value);
                $data->$key = $value;
            }
        }
    }
}

```

**Comment by ArturMoczulski** [comment]
@Hoten just tested. The frame arguments are being trimmed as expected. Are you sure the trimming is not occurring? It might be the case that even the trimmed payloads might be too big for `rollbar-agent` - I haven't been testing against that.

Adding an option for custom truncation strategy now.

**Comment by ArturMoczulski** [comment]
Closing the issue for now. @Hoten will reopen if there are further problems.
