### ISSUE TITLE
Add max items config option

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-php#391]
Similar to rollbar.js maxItems

**Comment by ArturMoczulski** [comment]
We need to clarify this more. In what context `maxItems` should limit the number of items reported? In the context of a single request? I believe that would be the most analogical to what Rollbar.js is doing. However, I'm not sure I'm convinced of the value of such an option. What are the use cases for this and why is it needed in PHP? @rivkahstandig3636 @rokob

**Comment by rivkahstandig3636** [comment]
@ArturMoczulski Yes, within a single request. This is a feature common to all of the SDKs (either currently supported or we plan to support it).

**Comment by ArturMoczulski** [comment]
This has been implemented in `master` and will be released in `v1.7.0`
