### ISSUE TITLE
Missed variable $scrubbedPayload definition in send method on FluentSender

### ISSUE THREAD

**Issue by gveraa** [rollbar/rollbar-php#393]
Missed variable $scrubbedPayload definition in send method

Pull request created for fix this
https://github.com/rollbar/rollbar-php/pull/392

**Comment by gveraa** [comment]
Hi,
do you have any estimated date on this bug fix?

Thanks

**Comment by ArturMoczulski** [comment]
It should be now fixed in release `v1.6.1`. Can you please double check that the fix works for you?

**Comment by gveraa** [comment]
Hi,
i check the change and still going to fail because when uuid is defined is
using undefined $scrubbedPayload.

Create new pull request.

Saludos

**Comment by ArturMoczulski** [comment]
Gotcha. My bad. PR merged in now.
