### ISSUE TITLE
Some support for CLI programs

### ISSUE THREAD

**Issue by vilius-g** [rollbar/rollbar-php#40]
As I understand, Rollbar is built with the assumption of an HTTP request. Still, it would be good to have at least some support for command line programs.

Now it just sets the URL to http://unknown/ and everything else to None. It makes very hard to determine in what context the error has occurred.

It would be nice if at least the command line arguments were included in the error details.

**Comment by brianr** [comment]
Agreed @vilius-g -- better support for CLI makes good sense.

If you want to take a stab at this, the things to do are:

- detect whether we're running in a web request or CLI
- if CLI:
  - don't gather or include request data - see [relevant code](https://github.com/rollbar/rollbar-php/blob/master/rollbar.php#L258)
  - do gather the command line args, and send them as server.argv - see [build_server_data()](https://github.com/rollbar/rollbar-php/blob/master/rollbar.php#L627)

**Comment by nodesocket** [comment]
To detect if a cli or web request, the following should work:

    $cli = false;
    if(strtolower(php_sapi_name()) === "cli") {
       $cli = true;
    } else {
        $cli = false;
    }

**Comment by nocive** [comment]
:+1: this is something we really miss after switching to rollbar as our primary error reporting tool

**Comment by Crisfole** [comment]
#80
