### ISSUE TITLE
Extension not working at all and gives error.

### ISSUE THREAD

**Issue by im-jc** [rollbar/rollbar-php#400]
Here are the points with errors.
1. Installation.
In your readme file following step is mentioned.
"Add rollbar-magento2 as a dependency in composer.json of your project and run composer update."
BUT what is the version? composer needs module version to be run command.

=> I have manually installed it by uploading files to app/code/Rollbar/Magento2.
Run both upgrade and compile commands successfully.

2. Added access token as following which is the correct way.
  ```
'rollbar' => 
  array (
    'access_token' => 'MY-TOKEN',
  )
```  

3. Now when i run site on frontend or in open magento admin then it gives HTTP ERROR 500.

Then i checked in logs and get the following error.
[E_ERROR] Uncaught Error: Class 'Rollbar\Magento2' not found in /chroot/home/app/code/Rollbar/Magento2/Plugin/InitPlugin.php:13

What to do now? Please provide support or upgrade your extension because magento standards are not maintained in xml files and any other files.

**Comment by rivkahstandig3636** [comment]
@im-jc I'm opening this as an issue in the magento2 repo and will have our SDK engineer take a look at this immediately.

**Comment by rivkahstandig3636** [comment]
Ah I see it's already open there. Closing it here.
