### ISSUE TITLE
Scrubbing every thing not just _POST and _SESSION

### ISSUE THREAD

**Issue by igloocube** [rollbar/rollbar-php#409]
Hi

Docs say for `$config['scrub_fields']`:

> An array of field names to scrub out of _POST and _SESSION

If I set `$config['scrub_fields'] = ['name'];` for example, POST fields are scrubbed as expected but also the 'notifier.name' param that is automatically supplied is as well.

Simple example:
```
Rollbar::init(
    [
        'access_token' => 'xxxxxxx',
        'environment' => 'development',
        'scrub_fields' => ['name']
    ]
);

Rollbar::log(
    Level::INFO,
    'testing'
);
```

Output on the occurance page:
> notifier.name | ********

**Comment by igloocube** [comment]
Also, is there a work around? Setting it to 'POST.name' or 'request.POST.name' has no effect at all. 

```
Rollbar::init(
    [
        'access_token' => 'xxxxxxx',
        'environment' => 'development',
        'scrub_fields' => ['request.POST.name']
    ]
);


$_POST = [
    'name' => 'joe'
];

Rollbar::log(
    Level::INFO,
    'testing',
    $_POST
);
```

body.message.name and request.POST.name still display 'Joe' under params on the occurrence page.

**Comment by igloocube** [comment]
Or alternatively, can we tell it not to include request.GET and request.POST etc when passing custom data so I can specifically tell it what to log and stop this leak of form data?

Example:
```
Rollbar::init(
    [
        'access_token' => 'xxxxxxxx',
        'environment' => 'development'
    ]
);


$testArray = [
    'some' => 'thing'
];

Rollbar::log(
    Level::INFO,
    'testing',
    $testArray
);
```

Includes $testArray and $_POST (but empty as [] in this simple example) and $_GET (same as POST).

**Comment by ajtran** [comment]
Hi there,

I apologize for the confusion. The field names in scrub fields will scrub out data from the entire payload. I believe the documentation is out of date. I can update that now.

As for more fine-tuned scrubbing and customizing of the payload, the best approach to implementing this is by passing a transformer function to the transform in the configuration as seen in the code here - https://github.com/rollbar/rollbar-php/blob/251c13c14f00d65d9bfe504f2726b2f1df15d7dd/src/Config.php#L504

And for more of a concrete example, please check out the examples here - https://github.com/rollbar/rollbar-php-examples/tree/master/transformer

**Comment by igloocube** [comment]
Thank you @ajtran 

Can it be made clear in the documentation of what data is included beyond what you specifically include too?

**Comment by ajtran** [comment]
@igloocube I believe it should be clear here - https://docs.rollbar.com/docs/php#section-configuration-reference

"An array of field names to scrub out of the entire payload excluding the top level access_token. Values will be replaced with asterisks. If overriding, make sure to list all fields you want to scrub, not just fields you want to add to the default. Param names are converted to lowercase before comparing against the scrub list.

Note: watch out to not overlap scrub fields with the keys of the Rollbar API request format. For example, scrubbing for field request will result in scrubbing all of the request content and API will respond with a 400 error.

Default: ('passwd', 'password', 'secret', 'confirm_password', 'password_confirmation', 'auth_token', 'csrf_token')"
