### ISSUE TITLE
json_encode: invalid utf-8 sequence in argument (in $_GET/$_POST keys)

### ISSUE THREAD

**Issue by rfink** [rollbar/rollbar-php#41]
Similar issue to the $_GET/$_POST *values*, but now it's on the keys.  Can be seen with common vulnerability scanners.  Example:

http://{yourdomainname.com}/{somepath}?acux8277%C0%BEz1%C0%BCz2a%90bcxuca8277

With:
display_errors Off (this is the only condition that causes the json_encode warning to happen)

Pull request coming shortly

**Comment by dlsteuer** [comment]
This has been completed and released.
