### ISSUE TITLE
Duplicated text in error message

### ISSUE THREAD

**Issue by djibarian** [rollbar/rollbar-php#413]
Just updated Rollbar from and old 0.15 version to the latest with Composer and suddenly the messages coming are duplicated. Some examples:

`#5465 E_NOTICE: Undefined index:: Undefined index: lists`

`#5468 E_USER_ERROR: Invalid User Id ("password"): Invalid User Id ("password”)`

where it should be

`#5465 E_NOTICE: Undefined index: lists`

`#5468 E_USER_ERROR: Invalid User Id ("password")`

**Comment by jessewgibbs** [comment]
@djibarian thanks for bringing this to our attention. 

Are these uncaught exceptions or explicit calls to Rollbar?  Also, can you tell us a bit more about the environment in which you're running Rollbar (PHP version, any frameworks + their version, etc.)?

**Comment by jessewgibbs** [comment]
Got it, thanks for the info.  We'll start working on reproducing this on our end.

**Comment by ArturMoczulski** [comment]
@djibarian this has been fixed in `master` now and will be released in upcoming `v1.6.4`
