### ISSUE TITLE
Implement cycle checks for serialization

### ISSUE THREAD

**Issue by coryvirok** [rollbar/rollbar-php#416]
In the case where we dump local variables and there are nested references to a shared object, we will end up serializing the nested loops multiple times. We've implemented a max depth option which is good but not a complete solution. [Other SDKs](https://github.com/rollbar/pyrollbar/blob/master/rollbar/lib/traverse.py#L94) implement cycle checking in order to detect if an object has already been serialized.

cc @rokob

**Comment by ArturMoczulski** [comment]
This has been implemented in PR #417
