### ISSUE TITLE
Rollbar Fails Silently with Wrong Access Token

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-php#421]
internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/19414319555

A user was struggling to debug the issue for why the data wasn't being sent to Rollbar. Turns out the access token was incorrect, but the user didn't realize this because the notifier failed silently.

**Comment by ArturMoczulski** [comment]
This is intended behavior. We do not have knowledge of how local logging is handled in user applications and can not assume a logging solution. Rollbar's logging methods, i.e. `\Rollbar\Rollbar::log` and `$logger->log` return a response object with the details of the result of the report. In case of a wrong access token, the code `var_dump(\Rollbar\Rollbar::info('Info Message'));` returns the following:

```
object(Rollbar\Response)#49 (3) {
  ["status":"Rollbar\Response":private]=>
  int(403)
  ["info":"Rollbar\Response":private]=>
  array(2) {
    ["err"]=>
    int(1)
    ["message"]=>
    string(56) "access token not found: eb2561a52efb4d4bba5a1d4b68be13e8"
  }
  ["uuid":"Rollbar\Response":private]=>
  string(36) "859ae783-49a1-41b5-a405-d0e65eb574bf"
}
```

It's up to the user use this information and pass it into his project's logging system - whatever it is (even if it's simple `echo`). We try to make this easier in additional SDKs for popular frameworks like Laravel or Symfony, but we still don't support a CodeIgniter SDK. If you are using CodeIgniter, you need to manually pass this data to CI's logging system.
