### ISSUE TITLE
Truncation constant doesn't seem to match documentation

### ISSUE THREAD

**Issue by Ramapitecus** [rollbar/rollbar-php#424]
In the file Truncation.php I can see this line:   `const MAX_PAYLOAD_SIZE = 524288; // 512 * 1024`
But according to the docs here: https://docs.rollbar.com/reference#section-http-responses 
The limit is 128kb. 

(I'm using rollbar-laravel in a laravel 5.0 project, but I still see it here on master)

**Comment by jessewgibbs** [comment]
@ArturMoczulski can you take a look at this?

**Comment by ArturMoczulski** [comment]
Thanks @Ramapitecus for catching this. I pushed a fix to `master` matching the latest documentation guidelines.
