### ISSUE TITLE
StringStrategy.php bug setting $strlen

### ISSUE THREAD

**Issue by Ramapitecus** [rollbar/rollbar-php#425]
On this line `if (is_string($value) && $strlen = strlen($value) > $threshold) {`  `$strlen` will be set to a boolean, and here `$payload->decreaseSize($strlen - $threshold);` it will be cast to either 0 or 1 and I don't think this is the intention.

**Comment by jessewgibbs** [comment]
@ArturMoczulski can you have a look at this?

**Comment by ArturMoczulski** [comment]
Thanks for catching this @Ramapitecus . It's been fixed in `master`.
