### ISSUE TITLE
Not all keys traversed.

### ISSUE THREAD

**Issue by Ramapitecus** [rollbar/rollbar-php#427]
https://github.com/rollbar/rollbar-php/blob/c2f8be87983ecdd3c46ceb3c459de02376af4707/src/Truncation/StringsStrategy.php#L41

On this line, if `$data` is an Array of arrays, it will return on the first `$value` and not process the rest of the keys. 
maybe: `   $modified = $modified || $this->traverse($value, $threshold, $payload);` would work.

**Comment by ArturMoczulski** [comment]
@Ramapitecus great catch.  Fixed in `master` now.
