### ISSUE TITLE
EncodedPayload constructor does not set size of encoded properties

### ISSUE THREAD

**Issue by Ramapitecus** [rollbar/rollbar-php#428]
https://github.com/rollbar/rollbar-php/blob/c2f8be87983ecdd3c46ceb3c459de02376af4707/src/Payload/EncodedPayload.php#L11

By not setting these properties. calling `size()` after construction returns `0` and `__toString()` returns `NULL` as well as `encoded()`

**Comment by ArturMoczulski** [comment]
This is intended. To provide `size` and `encoded` right after construction would require to run `json_encode` in the constructor. We do not want to do that as it will double the performance hit of json serialization. We are postponing calculating those properties until the execution of the `encode` method.

**Comment by Ramapitecus** [comment]
I thought It might be an optimization. It hasn't caused problems for me outside of some tests I've written. It's ok to close it. Thanks
