### ISSUE TITLE
Loosen monolog requirement to || ^2.0 or remove it

### ISSUE THREAD

**Issue by rtek** [rollbar/rollbar-php#432]
Monolog is currently at 2.0 beta - Can you allow || ^2.0 in the requires or remove it per #380

**Comment by jessewgibbs** [comment]
@ArturMoczulski what do you think?

**Comment by ArturMoczulski** [comment]
@rtek thanks for bringing this up. Yes, it's time for us to drop the legacy Monolog dependency. Monolog `v2.0.0-beta` has included our Monolog handler.

I am still leaving in the legacy `src/Monolog/Handler/RollbarHandler.php` for those who are still using this solution, however, I am dropping the dependency on monolog from `composer.json`. Meaning, now if you want to use the legacy solution, you will have to take care of the Monolog dependency on your own. Info on this has been outlined here: https://github.com/rollbar/rollbar-php/blob/master/src/Monolog/Handler/RollbarHandler.php#L13-L20

This has been committed to `master` and will be included in the upcoming release.
