### ISSUE TITLE
scrub_fields are not case insensitive

### ISSUE THREAD

**Issue by hubie** [rollbar/rollbar-php#434]
According to [the docs](https://docs.rollbar.com/docs/php-configuration-reference), the parameters will be converted to lowercase prior to comparing with `scrub_fields`.  Unfortunately this is not happening as a scrub_field of `my_password` won't scrub `MY_PASSWORD` from the data but a scrub_field of `MY_PASSWORD` will.

**Comment by jessewgibbs** [comment]
@hubie thanks for bringing this to our attention.  Which version of rollbar-php are you using?

**Comment by hubie** [comment]
We found the issue on 1.7.1, but I was able to confirm the behavior on the latest `master` version as well.
