### ISSUE TITLE
Reported URL errantly being reported as https://domain:80/...

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar-php#439]
In at least some cases, the URL this library is reporting contains an errant port 80 when the scheme is https, e.g. `https://mydomain.com:80/some/file.php`. This has been observed in versions 0.18.2 and 1.7.5.

**Comment by danielmorell** [comment]
I think this is caused by an errant Apache configuration. I don't think this caused by the SDK but instead the web server sitting in front.
