### ISSUE TITLE
SSL Certificate Problem Fails Silently

### ISSUE THREAD

**Issue by jessicahsieh** [rollbar/rollbar-php#443]
On Windows7 (x64) test exceptions don't get logged to rollbar (they fail silently) when the PHP setting for SSL certificate ("curl.cainfo") is not configured.

Rollbar installed via Composer, on bare project, with PHP 7.1.4 and the code:

```
<?php
require_once "vendor/autoload.php";

use \Rollbar\Rollbar;
use \Rollbar\Payload\Level;
Rollbar::init(
array(
'access_token' => '41181a36929b4b89a259dd7971252eb3',
'environment' => 'production'
)
);

Rollbar::log(Level::info(), 'Test info message 2');
throw new Exception('Test exception 2');
```

the above code worked for ubuntu but not windows 7. 

Fix: installing and assigning the proper certificates fixed the issue, but it would be nice to get some indication of what the problem is instead of failing silently.

[Internal Support Ticket] (https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/21361136850)

**Comment by ArturMoczulski** [comment]
`Rollbar::log` methods return a response object which contains detailed information on the response from the API. In this particular case the Response object's dump is: 

```
object(Rollbar\Response)#121 (3) {
  ["status":"Rollbar\Response":private]=>
  int(0)
  ["info":"Rollbar\Response":private]=>
  string(126) "error setting certificate verify locations:
  CAfile: C:\Users\arturmoczulski\Downloads\cainfo.pem
  CApath: none"
  ["uuid":"Rollbar\Response":private]=>
  string(36) "02d511e5-e86e-406e-9775-154c8406f284"
}
```
If you want to act on error-like situations you can do it like this:

```
$response = Rollbar::log(Level::ERROR, $e);

if ($response->getStatus() == 0) {
...
}
```
