### ISSUE TITLE
composer vendor code context

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php#445]
Rollbar reports invalid code context for vendor dependencies in PHP, such as:

This context will never be resolved since it’s not part of the project repository – vendor/ is managed by Composer and (should) be excluded from VCS. This can be improved a few ways:

1) Easy - just show the trace with no source option for vendor/ files

2) Medium – search the packagist API for the vendor/<vendor>/<package> and try to link to the master

3) Hard – require the user to include their composer.lock to resolve the actual source link

More info: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/conversation/21560351498

**Comment by brianr** [comment]
(1) is doable today with a backend code change (we have other cases like this, e.g. for Ruby). 2 and especially 3 would be quite neat.

**Comment by danielmorell** [comment]
It looks like we implemented (1) a while ago.
