### ISSUE TITLE
Class 'Monolog\Logger' not found

### ISSUE THREAD

**Issue by yangatgstdev** [rollbar/rollbar-php#457]
Updating rollbar/rollbar (v1.7.5 => v1.8.0)

Fatal error: Uncaught Error: Class 'Monolog\Logger' not found in /Users/LY/Server/Gstdev/Systemsurveyor/src/www/vendor/rollbar/rollbar/src/Config.php:366 Stack trace: #0 

I can't find monolog in the vendor folder.

**Comment by SimonBackx** [comment]
Same here

**Comment by ctxkiwi** [comment]
![](https://startupyard.com/wp-content/uploads/2017/04/f60db82acb9510030d2cf396c5bfa087_its-fine-the-anthem-of-meme-everything-is-fine-fire_1280-720.jpeg)

**Comment by ArturMoczulski** [comment]
My bad. Fixed in https://github.com/rollbar/rollbar-php/releases/tag/v1.8.1 and published to composer.
