### ISSUE TITLE
Error message on Traceback screen: "Unable to load code context!" (PHP)

### ISSUE THREAD

**Issue by pqr** [rollbar/rollbar-php#481]
Installed composer package rollbar/rollbar v1.8.1
PHP 7.4.2

I've made a setup for code context tracing following the instructions: https://docs.rollbar.com/docs/code-context

Integration with Source Controll BitBucket is also established.

My configuration:
```php
$config = [
    'access_token' => '...',
    'environment' => 'production',
    'included_errno' => E_ALL,
    'root' => dirname(__DIR__),
    'allow_exec' => false,
    'code_version' => App::getVersion(),
    'include_error_code_context' => true,
    'include_exception_code_context' => true,
    'include_raw_request_body' => true,
    'send_message_trace' => true,
];

Rollbar::init($config);
```

But on the web interface in "Traceback" tab I see error message:  "Unable to load code context!"

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/451007/77519822-3c58fe80-6e91-11ea-8dd8-5157340e56be.png">

How to setup correctly? Am I missing something in configuration?

**Comment by pqr** [comment]
I've made a few more tests and found, that context is actually passed to Rollbar servers correctly, I can see it on rollbar web interface in Raw JSON representation:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/451007/77559069-c3779800-6ecc-11ea-9a33-7fec9ac92b1e.png">

But on "Traceback" tab I see error message "unable to load code context" - could you please to fix it?

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/451007/77559164-e0ac6680-6ecc-11ea-89c9-9a878ecbd9b9.png">

**Comment by letaniaferreira** [comment]
Hello,

I have worked with you on this problem and you solved this issue by disconnecting from Bitbucket and then setting up a source control integration from scratch. I am gonna go ahead and close this issue now.
