### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by mingalevme** [rollbar/rollbar-php#484]
```
ErrorException: Trying to access array offset on value of type null
1. File "/app/vendor/rollbar/rollbar/src/RollbarLogger.php", line 121
..
```
The rows of the file:
```
...
} elseif ($response->getStatus() >= 400) {
    $info = $response->getInfo(); # Line 120
    $this->verboseLogger()->error('Occurrence rejected by the API: ' . $info['message']); # Line 121
}
...      
```

So `$info` can be null in some cases, but I don't know how to reproduce.

**Comment by lxlang** [comment]
I tried to fix this in my PR: https://github.com/rollbar/rollbar-php/pull/483


This happens, if you use php7.4 and Rollbar returns something invalid by API, which leads to a array access on a null. 

This is probably related to the latest API-outage of rollbar. See https://status.rollbar.com/incidents/zhq4g5th1f28

**Comment by ryan-deng-plastiq** [comment]
hey @lxlang  i had the same error in laravel - 

https://github.com/rollbar/rollbar-php-laravel/issues/99

**Comment by fgilio** [comment]
We've having this same error in Laravel too https://github.com/rollbar/rollbar-php-laravel/issues/99#issuecomment-637863602

**Comment by danielmorell** [comment]
This was fixed in https://github.com/rollbar/rollbar-php/releases/tag/v2.1.0
