### ISSUE TITLE
rollbar PHP memory error

### ISSUE THREAD

**Issue by kriit24** [rollbar/rollbar-php#498]
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /rollbar/vendor/rollbar/rollbar/src/Scrubber.php on line 81

Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/rollbar/vendor/rollbar/rollbar/src/DataBuilder.php on line 795

**Comment by bishopb** [comment]
PHP can consume quite a bit of memory for nested structures. Of course, 1G is quite a bit!

At first blush, I'm not sure we'll be able to do much about this with the code as implemented now: we're passing the data directly into `parse_str`, which is a black box and consumes as much memory as it needs to parse the given data structure. However, we may be able to optimize this for your particular use case if we had some details. Could you post:

1. What PHP version and server OS you're using
1. The value of the data you were passing (scrubbing any sensitive values)

**Comment by kriit24** [comment]
I wrote own error handler and for me this is not issue anymore

**Comment by kozie** [comment]
> I wrote own error handler and for me this is not issue anymore

Some elaboration would be nice just to see how you handled your particular challenge for future readers. If you could still do this, seeing it has already been a while, that would be great.
