### ISSUE TITLE
Option to exclude cookie data in request

### ISSUE THREAD

**Issue by dataground** [rollbar/rollbar-php#52]
The scrub_fields param should also look at $_COOKIE to exclude custom session cookies containing sensitive information. Maybe a scrub_cookies param?

**Comment by dataground** [comment]
Party related to https://github.com/rollbar/rollbar-php/issues/15

**Comment by ArturMoczulski** [comment]
This is covered by PR #126

**Comment by ArturMoczulski** [comment]
In master we don't include any $_COOKIE data in the request. This is not relevant anymore.
