### ISSUE TITLE
Prevent exception grouping

### ISSUE THREAD

**Issue by upklio** [rollbar/rollbar-php#535]
We're experiencing an annoying issue where Rollbar is grouping our exceptions with similar messages but where the date might change in them. For example, we'll see "foo 2021-06-13" on items screen, but when clicking through to occurrences the latest one is "foo 2021-06-14" - surely we should see the latest occurrence message on the items screen or be able to not group them.

TLDR; is there a way to prevent grouping exceptions on the message level (perhaps a bypass pattern) or on Rollbar Logger config level? Preferably without having to change grouping regex config within the Rollbar app?

**Comment by bxsx** [comment]
Hey @upklio

Thanks for reporting this and sorry for the confusion.
I've reported this issue to our internal team and will let you know when I receive any update on this.

**Comment by jmarronm** [comment]
Hi @upklio,

If the items are still valid we would need the links to them for proper analysis
New items/occurrences with similar grouping behavior would be also useful

Additionally, are we referring here to bugs (captured exceptions) or are they log messages captured as `Rollbar::report_message()`?

Thanks!

**Comment by bxsx** [comment]
Hi @upklio 

Optimistically, closing it as resolved. Please let us know if this should be reopened.
Thanks
