### ISSUE TITLE
Issue logging Symfony Doctrine errors

### ISSUE THREAD

**Issue by apphancer** [rollbar/rollbar-php#537]
It seems like errors with Symfony Doctrine (e.g. SQL errors) are not getting logged.

The `log()` method of RollbarLogger stops at `$serialized = $payload->serialize($this->config->getMaxNestingDepth());` and the response doesn't get sent.

This is happening with Symfony 5.3.3 and PHP 8.0.9

**Comment by bishopb** [comment]
Thanks @apphancer for the report. Let's see if we can get to the bottom of it. I'm seeking some clarification in the comments below.

> It seems like errors with Symfony Doctrine (e.g. SQL errors) are not getting logged.
> 
> The `log()` method of RollbarLogger stops at `$serialized = $payload->serialize($this->config->getMaxNestingDepth());` and the response doesn't get sent.

When you say "stops", do you mean the program exits? If so, is there some kind of PHP message being emitted, such as: `PHP Fatal error: Allowed memory size of 8388608 bytes exhausted`?

Or by "stops" do you mean the program stops making progress and just sits at that line?

Could you share the code you're using to invoke Rollbar as well as a sanitized example of the error being given to Rollbar?

> This is happening with Symfony 5.3.3 and PHP 8.0.9

To clarify, are you using [`rollbar-php-symfony-bundle`](https://github.com/rollbar/rollbar-php-symfony-bundle), or are you rolling your own use of `rollbar-php` inside of a Symfony-based app?

**Comment by danielmorell** [comment]
Closed due to inactivity.
