### ISSUE TITLE
Running rollbar in Lambda using Bref

### ISSUE THREAD

**Issue by alexkb** [rollbar/rollbar-php#553]
Hi there, we use rollbar-php for some Laravel applications and it works very well when the application is running under php-fpm on a container/server. However, if we try run the application in lambda with [bref](https://bref.sh/docs/), our exceptions aren't being logged to rollbar.

We've already made sure our lambda function has network access to make outgoing API calls to the internet, and we've made sure the configuration (token, etc) is set correctly, but still our errors aren't being received.

Is there anything we should be doing differently when rollbar-php run's inside lambda, as I know there are special steps if you're using rollbar in other languages if running in lambda ([such as node](https://docs.rollbar.com/docs/aws-lambda)). Thanks.

**Comment by bishopb** [comment]
Interesting question! A few thoughts come to mind...

* Do you see the traffic traversing the internet via the VPC Flow Logs?
* Does CloudWatch show any output?
* Is the access token populated into the environment and is the value correct?
* What version of PHP, rollbar-php, and (I assume) rollbar-php-laravel are you using?
* Are you using the FPM run time?

**Comment by alexkb** [comment]
Thanks for the reply @bishopb!
- Haven't looked at flow logs yet, but will try that shortly.
- Yes cloudwatch shows the Exception being thrown.
- php 8.0 with rollbar-laravel version 7.0 (Laravel v8.0). I just noticed rollbar-laravel uses rollbar-php 2.1.0 which doesn't support php 8.0, but it still works ok when running the application in a container.
- The lambda layer we use is "arn:aws:lambda:ap-southeast-2:209497400698:layer:php-80:9" which[ isn't the fpm version.](https://bref.sh/docs/runtimes/) I guess we could try it out as another test.

**Comment by bishopb** [comment]
> php 8.0 with rollbar-laravel version 7.0 (Laravel v8.0)

That specific combination may not work. I would recommend trying the 7.4 run time at this time. (Note that we're working on confirmed support for rollbar-laravel on php8 via rollbar-php v3.)

**Comment by alexkb** [comment]
Our application is built for php 8, so there would be quite a few changes required to downgrade to php 7.4.

If I used the latest version of rollbar-php via a fork of rollbar-php-laravel [here](https://github.com/MMEM/rollbar-php-laravel) (all it does is adjust the versions in composer), I can get errors logged to rollbar. One additional thing I had to do though was set my logging stack to go to 'rollbar' and 'stderr'. Previously it was 'rollbar', 'daily' and 'stdout' which somehow broke it.

I've tested this with both the fpm and non-fpm versions of bref's php layer, and it works fine in both.

A side note - occasionally we get rollbar errors logged as _"Rollbar\Payload\Frame::__construct(): Argument #1 ($filename) must be of type string, null given, called in /var/task/vendor/rollbar/rollbar/src/DataBuilder.php on line 479"_ instead of the real error. It doesn't happen often, so I will leave that for now.

**Comment by bishopb** [comment]
> Our application is built for php 8, so there would be quite a few changes required to downgrade to php 7.4.

Understood.

> (1) If I used the latest version of rollbar-php via a fork of rollbar-php-laravel [here](https://github.com/MMEM/rollbar-php-laravel) (all it does is adjust the versions in composer), I can get errors logged to rollbar.
> (2) One additional thing I had to do though was set my logging stack to go to 'rollbar' and 'stderr'. Previously it was 'rollbar', 'daily' and 'stdout' which somehow broke it. I've tested this with both the fpm and non-fpm versions of bref's php layer, and it works fine in both.

Ok, so as I understand it, if you do both #1 and #2 above, log messages from your Lambda arrive at Rollbar. Is that right? What happens if you set your logging stack to `'rollbar'`, `'daily'`, and `'stderr'`? (Maybe `'stdout'` is an issue.) When you say "broke" it, do you mean "doesn't send to Rollbar" or another kind of breakage?

> A side note - occasionally we get rollbar errors logged as _"Rollbar\Payload\Frame::__construct(): Argument 1 ($filename) must be of type string, null given, called in /var/task/vendor/rollbar/rollbar/src/DataBuilder.php on line 479"_ instead of the real error. It doesn't happen often, so I will leave that for now.

This is fixed by https://github.com/rollbar/rollbar-php/pull/552, which will be out as a 3.0.1.

**Comment by danielmorell** [comment]
I am closing this as it should be fixed now.
