### ISSUE TITLE
Deprecation error in PHP 8.1

### ISSUE THREAD

**Issue by janicekt** [rollbar/rollbar-php#555]
Hi,
when i want to run version 3.0 on php 8.1, it throws up a bug: 
`Deprecated: Rollbar\Payload\Notifier implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../vendor/rollbar/rollbar/src/Payload/Notifier.php on line 7`

**Comment by danielmorell** [comment]
This should be resolved in [v3.1.0](https://github.com/rollbar/rollbar-php/releases/tag/v3.1.0). You can read the discussion of the solution on #558.
