### ISSUE TITLE
Is Rollbar really bad or what's going on?

### ISSUE THREAD

**Issue by NinoSkopac** [rollbar/rollbar-php#556]
I've been using Rollbar for years. It worked okay/not always completely reliable.

Now I wanted to set up a new PHP project using the wizard, and the test event doesn't go through.

Why are both wizards advising me to use such an old version? Latest is 3.0 :D

<img width="1251" alt="Screenshot 2022-01-11 at 22 12 38" src="https://user-images.githubusercontent.com/1783732/148968813-a55c61d8-0602-493a-9916-2d383b94ce76.png">
<img width="804" alt="Screenshot 2022-01-11 at 22 12 47" src="https://user-images.githubusercontent.com/1783732/148968852-e2b48ff1-1e5b-4db7-84d8-f876189cb9d2.png">
 
I followed the troubleshooting steps and I can ping rollbar etc. I've had problems with Rollbar in previous projects but I didn't care enough to speak out. I just wasted 20 minutes trying to set this up - I could've already been done with the project :D

I've tried installing 3.0 as well but nothing's coming to the web dashboard.

finally, [this examples](https://docs.rollbar.com/docs/php#usage) worked

really bad customer experience because how can I rely on it now? Reliability should be your biggest selling point

**Comment by Bilge** [comment]
Rollbar lost to [Sentry](sentry.io/). Researching the market should be your responsibility.

**Comment by danielmorell** [comment]
The wizard has been updated.

**Comment by cyrusradfar** [comment]
@NinoSkopac consider there are more amiable ways of titling an issue that don't necessarily put down the entire company or any team within it.
