### ISSUE TITLE
Rollbar\\Payload\\Body::__construct(): Argument #1 ($value) must be of type Rollbar\\Payload\\ContentInterface, Rollbar\\Payload\\TraceChain given

### ISSUE THREAD

**Issue by stephpy** [rollbar/rollbar-php#559]
On Rollbar-php 3.1.0:

https://github.com/rollbar/rollbar-php/blob/master/src/DataBuilder.php#L409

Fail when getExceptionTrace returns a TraceChain since TraceChain has not the ContentInterface.
PR without BC break is coming.

**Comment by danielmorell** [comment]
Thank you for bringing this to our attention!
