### ISSUE TITLE
Plans for psr/log v.3?

### ISSUE THREAD

**Issue by Chris53897** [rollbar/rollbar-php#570]
Enhancement:

Hi,
Are there any plans to migrate from psr/log from v2 to v3 ?
I did a quick look into the code, and i think it is not so easy to change it.

[actual](https://github.com/rollbar/rollbar-php/blob/master/src/RollbarLogger.php#L92):
`#public function log($level, $toLog, array $context = array())`

[psr/log v.3](https://github.com/php-fig/log/blob/master/src/LoggerInterface.php#L124)
`public function log($level, string|\Stringable $message, array $context = []): void`

Problem 1 the return instead of void.
Problem 2 $toLog has a different type.

Maybe a solution could be to remove psr/log in the long term?
So usere are not tied to v1|v2

Greetz

**Comment by danielmorell** [comment]
This is a good question. You can find more details about the this topic here https://github.com/rollbar/rollbar-php-laravel/issues/128#issuecomment-1052377338.

**Comment by danielmorell** [comment]
Until we have a clear roadmap to v4 this is not really an option. I am going to close this issue for now, and we will revisit it once we start working on a v4.

**Comment by danielmorell** [comment]
This has been resolved and will be part of our v4.0 release.

**Comment by Chris53897** [comment]
@danielmorell Sounds good. Can you provide an UPGRADE.md in the 4.x Branch with infos what changed, and how to migrate v3 => v4?
Maybe the 5.x branch of https://github.com/rollbar/rollbar-php-symfony-bundle needs some changes to support v4.

**Comment by danielmorell** [comment]
@Chris53897 I added an issue to create upgrade documentation (see #599).

**Comment by danielmorell** [comment]
This was fixed in #577.
