### ISSUE TITLE
Uncaught ErrorException: Using the Serializable interface has been deprecated.

### ISSUE THREAD

**Issue by wrabit** [rollbar/rollbar-php#574]
After upgrading to latest rollbar, I'm getting an error being logged:

```
Symfony\Component\ErrorHandler\Error\FatalError: Uncaught ErrorException: Using the Serializable interface has been deprecated. in /vendor/rollbar/rollbar/src/Utilities.php:150
```

https://github.com/rollbar/rollbar-php/blob/d6ec7a387429b119c65105eed6b17ee4802b6119/src/DataBuilder.php#L1024

Any clue to what it is causing it?

**Comment by danielmorell** [comment]
Please update to rollbar/rollbar v3.1.3 and let me know if you still have this issue.

**Comment by wrabit** [comment]
It fixed it, thanks.
