### ISSUE TITLE
Monolog 3 support

### ISSUE THREAD

**Issue by acelaya** [rollbar/rollbar-php#575]
Is there any plans to add support for monolog 3?

**Comment by danielmorell** [comment]
This is a good question. You can find more details about the this topic here [rollbar/rollbar-php-laravel#128 (comment)](https://github.com/rollbar/rollbar-php-laravel/issues/128#issuecomment-1052377338).

Until we have a clear roadmap to v4 this is not really an option. I am going to close this issue for now, and we will revisit it once we start working on a v4.

**Comment by caseyamcl** [comment]
Now that v4-beta is out, is there any consideration for supporting Monolog v3?

**Comment by danielmorell** [comment]
Oops. I missed this one when working on the first v4 beta. I will try to add this to the next beta.
