### ISSUE TITLE
Invalid scrubling algo

### ISSUE THREAD

**Issue by dimkalinux** [rollbar/rollbar-php#61]
Hi.

In docs 'scrub_fields
Array of field names to scrub out of _POST and _SESSION. Values will be replaced with asterisks. If overridiing, make sure to list all fields you want to scrub, not just fields you want to add to the default. Param names are converted to lowercase before comparing against the scrub list.'

But actually comparing worked as case sensitivity in case target key is not defined in scrub_fields as regular expressions. And in session params not converting to lowercase.

**Comment by dimkalinux** [comment]
For example scrub_fields = array('password') and $_SESSION['PASSWORD'] will not be scrubled because you did simple in_array('password', array('PASSWORD'));

**Comment by dimkalinux** [comment]
Test passed because its covered by regular expressions /password/i

**Comment by brianr** [comment]
Thanks for the report, @dimkalinux . We'd be happy to accept a PR that fixes this if you are up for it; otherwise we'll get to it soon. As a workaround, it sounds like you should be able to use regexes (e.g. `"/password/i"`) instead of strings.

**Comment by dimkalinux** [comment]
https://github.com/rollbar/rollbar-php/pull/63

**Comment by brianr** [comment]
Fix released in version 0.15.0. Thanks again!
