### ISSUE TITLE
RollbarLogger::log() incompatible with Psr\Log\LoggerInterface::log()  v1.0

### ISSUE THREAD

**Issue by lukastaferner** [rollbar/rollbar-php#617]
Dear Rollbar-Team,
Installing the package with psr/log:^1 produces the following error:
Fatal error: Declaration of Rollbar\RollbarLogger::log($level, Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::log($level, $message, array $context = []) in /srv/apache2/keepersport/vendor/rollbar/rollbar/src/RollbarLogger.php on line 194

Thank you!

**Comment by Chris53897** [comment]
(I am not from the rollbar team)
I am not sure if it is possible to support psr/log 1-3. I did two PR and i suggest to remove support for version 1.
