### ISSUE TITLE
Exception message override log message

### ISSUE THREAD

**Issue by armetiz** [rollbar/rollbar-php#631]
Hi there.

```php
try {
    throw new \RuntimeException('Not yet implemented.');
} catch (\Throwable $exception) {
    $this->logger->error('User could not be registered.', [
        'exception' => $exception,
    ]);
}
```

The above Rollbar logged event message is : `Not yet implemented`. 
It should be `User could not be registered`.

**Comment by danielmorell** [comment]
Hey Thomas, thank you for reporting this!

I took a look at the implementation and `User could not be registered.` is being sent as the `description` if a `Throwable` is provided in the `'exception'` context. I agree this is probably backwards of the way I would have expected it given your code example above.

Given there are two messages associated with the error, we have three options (at least that I can think of):

1. Send the `Not yet implemented.` as the message and `User could not be registered.` as the description.
2. Send the `User could not be registered.` as the message and `Not yet implemented.` as the description.
3. Concatenate the two into one message e.g. `User could not be registered. (Not yet implemented.)`.

I think I lean toward option 3. What do you think?

**Comment by armetiz** [comment]
Hi @danielmorell ,
I think option 2. is the best one! This seems obvious to me because it respects developper intention's.

On the above example, you can see the exception line, but in real application errors are thrown in deeper code. When receiving Rollbar alert, developpers knows about theirs codes, but if message is related to a librairy exception.. It's really hard to understand on first sight.

Option 1 is inappropriate.
Option 3 : this is not a bad idea
