### ISSUE TITLE
Extended filtering

### ISSUE THREAD

**Issue by flowdee** [rollbar/rollbar-php#66]
My scenario: I need to filter the source of an error and want to prevent certain files to log errors.

Therefore It would be amazing to deliver a callback function to the Rollbar::init($config); which handles the final result and I can check / edit or refuse the api call.

**Comment by coryvirok** [comment]
Hi flowdee,

Thanks for the feature request. We will take a look.

**Comment by ArturMoczulski** [comment]
This is supported in v1.0.0 with config option `checkIgnore` that takes a callable. This issue can be closed.

**Comment by flowdee** [comment]
Thanks for the info @ArturMoczulski . Going to check it out soon

**Comment by rokob** [comment]
Closing because this is supported via checkIgnore
