### ISSUE TITLE
[Feature Request] Add an RollbarExceptionInterface

### ISSUE THREAD

**Issue by erichard** [rollbar/rollbar-php#68]
That would allow the `report_exception()` to automatically add extra_data and payload_data if the reported exception implements the `RollbarExceptionInterface`.

What do you think ?

**Comment by ArturMoczulski** [comment]
`report_exception()` is deprecated since `v1.0.0`. New implementation supports `$extra_data` so I'm not sure if this is still a feature request. I'm closing the issue for now, but @erichard please let us knows if you still have a request for a missing feature.
