### ISSUE TITLE
[Feature Request]: Try-catch block around 'person_fn'

### ISSUE THREAD

**Issue by davidsteinsland** [rollbar/rollbar-php#70]
Would be nice if the call to `person_fn` callable would be wrapped in a try-catch block, and swallow the exception (logging it with `log_error`).

The problem I had:
- PHP error was generated from PHP-PDO layer (connection warning)
- `person_fn` was called, which checks if a session exists and returns user information
- Sessions are stored in database, meaning that the session checking would again result in a PDO warning
- This would fail, as `report_php_error` would fail with "Exception while reporting php error".

**Comment by ArturMoczulski** [comment]
This is ready for review in https://github.com/rollbar/rollbar-php/pull/134

**Comment by rokob** [comment]
Merged
