### ISSUE TITLE
status 200 when using set_exception_handler

### ISSUE THREAD

**Issue by oadam** [rollbar/rollbar-php#72]
I'm using rollbar with great success but today I've noticed something that bothers me.

My code is using exception to report invalid GET parameters.
In dev, when I call an invalid URL, I get a 500 error and the error is logged by php.
In prod, where rollbar is enabled, I obtain a blank page with a 200 status.

Having a 200 status can be an issue for a number of reasons (for example because it means a search engine could index pages whose URL is invalid).

In my opinion, most people would like the server to return a 5XX status, so it makes sense to implement this in rollbar's `error_handler`.

Do you think that's a good idea ?

**Comment by Crisfole** [comment]
Hey there, sorry for the long delay!

I don't think we're purposely setting the status to 200. On my end I still get a 500 when I report something to Rollbar.

Are you sure this is the application and not your server in production? (Apache can easily do stuff like this, for example).

**Comment by nocive** [comment]
Seeing this exact same behaviour too after switching to php7.
It's definitely a rollbar related problem because when rollbar is not enabled everything works as expected.

**Comment by nocive** [comment]
See also https://github.com/getsentry/sentry-php/issues/280 for what seems like the same issue.

**Comment by ArturMoczulski** [comment]
This is ready for review in PR #143

**Comment by rokob** [comment]
Fixed in #143
