### ISSUE TITLE
Much Cleaner Code

### ISSUE THREAD

**Issue by alwaysontop617** [rollbar/rollbar-php#77]
Everytime I run a code check I am getting this:
![errors](https://cloud.githubusercontent.com/assets/17088079/14001964/ce81a598-f116-11e5-867a-1dd0687b9b46.png)

The yellow represents rollbar which if you can't read, has 1,216

**Comment by alwaysontop617** [comment]
https://poke-cmsd-dodiaraculus.c9users.io/code/style-report/

**Comment by Crisfole** [comment]
Hey there, what code checker/linter/inspetor, exactly, are you using? And does your tool tell you what the problem it's detected is? (I can't see the link you posted).

**Comment by alwaysontop617** [comment]
Crisfole: I use phpcheckstyle with php-cs-fixer but php-cs-fixer does not fix the code.

**Comment by alwaysontop617** [comment]
http://tecflare.com:3000/Tecflare/poKe_CMS

**Comment by Crisfole** [comment]
@alwaysontop617 Sorry that link is just your application. Can you re-send the actual style report?

**Comment by alwaysontop617** [comment]
@Crisfole ok

**Comment by alwaysontop617** [comment]
http://tecflare.com:3000/Tecflare/poKe_CMS/src/master/code/checkstyle_result

**Comment by alwaysontop617** [comment]
@Crisfole its here

**Comment by alwaysontop617** [comment]
https://github.com/rollbar/rollbar-php/pull/78

**Comment by Crisfole** [comment]
Hi there @alwaysontop617  I saw that, yes.

While we appreciate the issue report, we reserve that file for people who've contributed code through a PR (you'll notice it's really just a proxy for https://github.com/rollbar/rollbar-php/graphs/contributors).

At this time we're still evaluating whether or not any of the warnings there apply to the coding style we've chosen for Rollbar (which is consistent, although not the one you've personally chosen).

**Comment by alwaysontop617** [comment]
@Crisfole So how can I help?

**Comment by Crisfole** [comment]
It really sounds like our conventions don't match yours. Could you configure a `phpcheckstyle` configuration file that matches the existing conventions we're using so we can hook it into our tests?

**Comment by alwaysontop617** [comment]
Crisfole: Ya but phpcheckstyle needs me to be part of your organization. My username is alwaysontop617.

**Comment by alwaysontop617** [comment]
@Crisfole

**Comment by Crisfole** [comment]
Hi @alwaysontop617, we only add employees to the Rollbar organization (proprietary code and all).

I think you may have misunderstood my request. I'm looking for a PR with a new file(s) that configures phpcheckstyle so that our code *already* mostly passes. Most linters allow you to select what code inspections you want to run, including swapping out things like tabs/spaces, variable naming conventions. It looks like there's a pile of xml files in the `config` folder.

**Comment by alwaysontop617** [comment]
@Crisfole Im going to need lots of help its not as easy as 1 2 3. Seriously

**Comment by Crisfole** [comment]
Alright. What help do you need?

**Comment by alwaysontop617** [comment]
Well Were going to have to do live coding. I can use c9.io and share it
with you. Can you get on at 3/28/16 at
8:00 AM
Tuesday, 3/28/16 (CDT)
Time in Plano, TX, United States

On Mon, Mar 28, 2016 at 11:23 AM, Christopher Pfohl <
notifications@github.com> wrote:

> Alright. What help do you need?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rollbar/rollbar-php/issues/77#issuecomment-202470372>
>



-- 
Sincerely,
Thomas Wilbur

**Comment by Crisfole** [comment]
Hey there, no can do, sorry! I'm quite busy.

If you have a specific support request I'm happy to answer any questions you have, and if you submit *anything* in a PR we can discuss what you've come up with much more readily.

**Comment by Crisfole** [comment]
I'm going to close this in factor of #81.
