### ISSUE TITLE
Rollbar class not found when using composer

### ISSUE THREAD

**Issue by ytn3rd** [rollbar/rollbar-php#79]
We got rollbar through composer and the file exists. When we try include autoload.php it can not find the Rollbar class.

> [Fri Apr 08 04:56:06.625637 2016] [:error] [pid 7389] [client xxx.xxx.xxx.xxx:57535] PHP Fatal error:  Class 'Rollbar' not found in /var/www/somepath/htdocs/test.php on line 10

However if we include the rollbar.php file directly it works fine. See example below

```
// Does not work
//require_once '../vendor/autoload.php';

// Does owrk
require_once '../vendor/rollbar/rollbar/src/rollbar.php';

$config['access_token'] = '.....';
Rollbar::init($config);
```

I am unsure why as
`"classmap": ["src/rollbar.php"]`
matches what some other projects use just fine.

**Comment by Crisfole** [comment]
Hey there, I just installed rollbar with composer to run a quick test and I'm not getting the same results.

Are other composer-installed packages working correctly with autoload in your test file?

**Comment by ytn3rd** [comment]
We are using quite a few and they all work fine (codescale/ffmpeg-php, abeautifulsite/simpleimage, aws/aws-sdk-php, google/apiclient, facebook/php-sdk-v4, stripe/stripe-php, abraham/twitteroauth, happyr/linkedin-api-client, mixpanel/mixpanel-php, phpmailer/phpmailer, calcinai/xero-php and of course rollbar/rollbar).

Using an Amazon Linux AMI on Amazon EC2 that is fully up to date.

Roller version is ~0.15.0.

**Comment by Crisfole** [comment]
Have you tried uninstalling and reinstalling Rollbar?

**Comment by ytn3rd** [comment]
I had not tried uninstall and reinstall. I did however just install Rollbar on different server with composer, and it worked fine. Will close this now because it appears it must be something on our end, not on your end.

**Comment by elgeorge2k** [comment]
I had the exact same issue: rollbar working on production with composer, but not in development becase "Class 'Rollbar' not found "

**Comment by Crisfole** [comment]
@elgeorge2k have you tried removing and re-adding the file?

**Comment by elgeorge2k** [comment]
Hey guys sorry this was resolved, perhaps it was something with composer.

**Comment by tandemloop** [comment]
Getting the same error now

**Comment by emresaracoglu** [comment]
> 
> 
> Getting the same error now

Me too
