### ISSUE TITLE
Gather PHP version info

### ISSUE THREAD

**Issue by Crisfole** [rollbar/rollbar-php#84]

**Comment by ArturMoczulski** [comment]
I need a bit more explanation on this as well. Where should the version info be gathered? I assume this is about adding that information to the Payload, is that correct? I can see this being done already here: https://github.com/rollbar/rollbar-php/blob/master/src/DataBuilder.php#L466-L469

**Comment by coryvirok** [comment]
Oh, great. Ya that should be all we need. Closing.
