### ISSUE TITLE
PSR

### ISSUE THREAD

**Issue by megazoll** [rollbar/rollbar-php#9]
What's about supporting PSR?
https://github.com/php-fig/fig-standards/tree/master/accepted

**Comment by lindyhopchris** [comment]
+1 for also making the PSR compatible. Personally I don't think this should become version 1.0 until it is PSR compliant.

**Comment by mbrevda** [comment]
As a partial workaround, monolog has a roolbar handler that provides a psr-3 interface: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RollbarHandler.php

**Comment by baohx2000** [comment]
thanks @mbrevda for the note about the monolog handler
@brianr you could always start a v2 branch which we'd PR against to make PSR compliant.  That way you could go ahead and 1.0 the current code if want.  It's not expected that major versions be backwards compatible.

**Comment by rlweb** [comment]
+1

**Comment by theofidry** [comment]
>Would gladly accept a pull request, as long as it doesn't break backwards compatibility

Then why not using Semver? The large majority of PHP libraries are using semver, by having releases `0.*.*` you are indicating it is still a development version with risk of BC, which is apparently not the case as you don't want to introduce any BC.

**Comment by ArturMoczulski** [comment]
1. PSR-1 compliant
2. PSR-2 compliant
3. PSR-3 to check
4. PSR-4 to check
5. PSR-6 to check
6. PSR-7 to check
7. PSR-11 to check
8. PSR-13 to check
9. PSR-16 to check

**Comment by rokob** [comment]
Merged
