### ISSUE TITLE
Redirect after error report

### ISSUE THREAD

**Issue by pobegov** [rollbar/rollbar-php#99]
Hi,

in production we don't want to stop rendering the page in case of whatever error has happened, and redirect to a nice error message page instead. I failed to locate anything in this direction in the notifier, is there a best-practice approach for this?

thanks!

**Comment by rivkahstandig3636** [comment]
Hi @pobegov!

This isn't a built in functionality in the notifier, but I did find this [blog post ](http://markonphp.com/handling-fatal-errors-php/) that may be able to help you redirect to an error page instead of just ending up on a blank page after a fatal error. Hope this helped!
